### ISSUE TITLE
Error in babel at launch time

### ISSUE THREAD

**Issue by Xenosender** [Inist-CNRS/lodex#1065]
Hi

I'm trying to start lodex and, be it from npm or docker, I get the same error (here from docker) :

`
> lodex@11.10.2 start /app
lodex_1  | > node --require @babel/register src/api
lodex_1  | 
lodex_1  | /app/node_modules/@babel/runtime/helpers/inherits.js:5
lodex_1  |     throw new TypeError("Super expression must either be null or a function");
lodex_1  |     ^
lodex_1  | 
lodex_1  | TypeError: Super expression must either be null or a function
lodex_1  |     at _inherits (/app/node_modules/@babel/runtime/helpers/inherits.js:5:11)
lodex_1  |     at /app/node_modules/react-event-listener/dist/react-event-listener.cjs.js:119:3
lodex_1  |     at Object.<anonymous> (/app/node_modules/react-event-listener/dist/react-event-listener.cjs.js:167:2)
lodex_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
lodex_1  |     at Module._compile (/app/node_modules/pirates/lib/index.js:99:24)
lodex_1  |     at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
lodex_1  |     at Object.newLoader [as .js] (/app/node_modules/pirates/lib/index.js:104:7)
lodex_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
lodex_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
lodex_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
lodex_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
lodex_1  |     at require (internal/modules/cjs/helpers.js:25:18)
lodex_1  |     at Object.<anonymous> (/app/node_modules/material-ui/TextField/EnhancedTextarea.js:47:27)
lodex_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
lodex_1  |     at Module._compile (/app/node_modules/pirates/lib/index.js:99:24)
lodex_1  |     at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
lodex_1  |     at Object.newLoader [as .js] (/app/node_modules/pirates/lib/index.js:104:7)
lodex_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
lodex_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
lodex_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
lodex_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
lodex_1  |     at require (internal/modules/cjs/helpers.js:25:18)
lodex_1  | npm ERR! code ELIFECYCLE
lodex_1  | npm ERR! errno 1
lodex_1  | npm ERR! lodex@11.10.2 start: `node --require @babel/register src/api`
lodex_1  | npm ERR! Exit status 1
lodex_1  | npm ERR! 
lodex_1  | npm ERR! Failed at the lodex@11.10.2 start script.
lodex_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lodex_1  | 
lodex_1  | npm ERR! A complete log of this run can be found in:
lodex_1  | npm ERR!     /root/.npm/_logs/2020-03-06T15_06_55_559Z-debug.log
lodex_lodex_1 exited with code 1
`

This is from the latest release (11.10.2) with npm 6.13.14, node 8.17.0, docker 19.03.6

**Comment by touv** [comment]
Perhaps, a node version incompatible...  you can test with docker-compose
```
git clone https://github.com/Inist-CNRS/lodex
cd lodex
docker-compose up 
```

**Comment by Xenosender** [comment]
Thanks for replying quickly
As I said, I tested both methods (from node and from docker) and both raise the same error...

**Comment by Xenosender** [comment]
Problem was solved by using node 11.
I think the README is not up to date
