### ISSUE TITLE
Path error on main page results in blank page

### ISSUE THREAD

**Issue by Xenosender** [Inist-CNRS/lodex#1066]
Hi
I'm trying to use v11.10.1  (node 8.17.0).
Though the admin page displays fine, the main page (http://localhost:3000/) has a lot of react errors, which result in a blank page.
The errors also show in the logs :

`
Server listening on port 3000
Press CTRL+C to stop server
Warning: Failed prop type: Invalid prop "path" supplied to "Route".
    in Route
    in Routes
    in Connect(Routes)
    in MuiThemeProvider
    in Provider
    in Context.Provider
    in Router
    in StaticRouter
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: SideEffect(NullComponent)
Warning: Failed prop type: The prop "resource.uri" is marked as required in "DatasetCharacteristicItemComponent", but its value is "undefined".
    in DatasetCharacteristicItemComponent
    in Connect(DatasetCharacteristicItemComponent)
    in div
    in div
    in DatasetCharacteristicsView
    in Connect(DatasetCharacteristicsView)
    in div
    in div
    in HomeComponent
    in Translated(HomeComponent)
    in Connect(Translated(HomeComponent))
    in Context.Provider
    in Context.Consumer
    in Route
    in Fragment
    in Context.Provider
    in Router
    in ConnectedRouter
    in Connect(ConnectedRouter)
    in div
    in div
    in AppComponent
    in Routes
    in Connect(Routes)
    in MuiThemeProvider
    in Provider
    in Context.Provider
    in Router
    in StaticRouter
Warning: Failed prop type: The prop "handleOpen" is marked as required in "PureButtonWithDialogForm", but its value is "undefined".
    in PureButtonWithDialogForm
    in Translated(PureButtonWithDialogForm)
    in withHandlers(Translated(PureButtonWithDialogForm))
    in Connect(withHandlers(Translated(PureButtonWithDialogForm)))
    in CreateResource
    in Connect(CreateResource)
    in Translated(CreateResource)
    in Context.Provider
    in Context.Consumer
    in Route
    in Fragment
    in Context.Provider
    in Router
    in ConnectedRouter
    in Connect(ConnectedRouter)
    in div
    in div
    in AppComponent
    in Routes
    in Connect(Routes)
    in MuiThemeProvider
    in Provider
    in Context.Provider
    in Router
    in StaticRouter
`

It seems like there is a path problem somewhere.
I followed the instructions (setting EZMASTER_PUBLIC_URL to http://localhost:3000) but in my setup, I'm trying to get lodex to work on a remote server accessible through the address 192.168.1.18:3000
Did I mess up the configuration ?
Or is it a React problem ?

Thanks for your help!

**Comment by touv** [comment]
All React warnings can be ignored ...
 
Can you attach a sample of your data and your model you used ?

If that helps, there is a dedicated repository with some examples of data and models https://github.com/Inist-CNRS/lodex-use-cases/tree/master/films

**Comment by Xenosender** [comment]
Again, problem solved with node 11.
