### ISSUE TITLE
Column editing panel is overwritten by "Add to publication" button

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#133]
In version 5.6.0, when `uri` is clicked in backoffice, you get a new panel, but overwritten by `Add to publication` buttons.

![image](https://cloud.githubusercontent.com/assets/595509/23743622/a3ac2d02-04b1-11e7-88ba-8e82c77d4165.png)

**Comment by djhi** [comment]
Fix in [5.12.0](https://github.com/Inist-CNRS/lodex/releases/tag/v5.12.0)
