### ISSUE TITLE
 [MongoError]: failed to connect to server

### ISSUE THREAD

**Issue by dieubenit** [Inist-CNRS/lodex#1441]
Hello, 
If you can help me. 
After the deployment of lodex I have the following error: 

lodex-lodex-1  | More info about useBuiltIns: https://babeljs.io/docs/en/babel-preset-env#usebuiltins
lodex-lodex-1  | More info about core-js: https://babeljs.io/docs/en/babel-preset-env#corejs
lodex-lodex-1  | Mon, 20 Jun 2022 08:58:25 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at src/api/index.js:92:5
lodex-lodex-1  | Server listening on port 3000
lodex-lodex-1  | Press CTRL+C to stop server
lodex-lodex-1  | Error [MongoError]: failed to connect to server [undefined:27017] on first connect [Error: getaddrinfo EAI_AGAIN undefined
lodex-lodex-1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
lodex-lodex-1  |   name: 'MongoError'
lodex-lodex-1  | }]
lodex-lodex-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
lodex-lodex-1  |     at Pool.emit (events.js:314:20)
lodex-lodex-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
lodex-lodex-1  |     at Object.onceWrapper (events.js:421:26)
lodex-lodex-1  |     at Connection.emit (events.js:314:20)
lodex-lodex-1  |     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
lodex-lodex-1  |     at Object.onceWrapper (events.js:421:26)
lodex-lodex-1  |     at Socket.emit (events.js:314:20)
lodex-lodex-1  |     at emitErrorNT (internal/streams/destroy.js:92:8)
lodex-lodex-1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
lodex-lodex-1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
lodex-lodex-1  | (node:30) UnhandledPromiseRejectionWarning: Error: L'url de la base mongoDB n'est pas bonne, ou non renseignée.
lodex-lodex-1  |     at /app/src/api/services/mongoClient.js:16:19
lodex-lodex-1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)

I applied the solution proposed by Mr. Fr.... to put the mongodb connection configuration in config.json

{
	"mongo": {
		"host": "mongo:27017"
	},

}

But I still have the error message. 
Thank you for your help.

**Comment by parmentf** [comment]
Which way did you use to start lodex?

I mean, `make start` should start lodex *and* mongo.

PS: for reference: #1440

**Comment by dieubenit** [comment]
Hello, 

I used **make start**, this is where I encounter the problem.

**Comment by parmentf** [comment]
The error says:

```txt
lodex-lodex-1 | (node:30) UnhandledPromiseRejectionWarning: Error: L'url de la base mongoDB n'est pas bonne, ou non renseignée.
lodex-lodex-1 | at /app/src/api/services/mongoClient.js:16:19
```

This implies a configuration problem.

```txt
lodex-lodex-1 | Error [MongoError]: failed to connect to server [undefined:27017] on first connect [Error: getaddrinfo EAI_AGAIN
```

shows that the mongo hostname is `undefined`...

**Comment by dieubenit** [comment]
Hello, 
Here is my configuration in config.json

{
                "mongo": {
                "host": "mongodb://127.0.0.1:27017"
            },
            }

I have installed portainer and I connect with the portainer which gives me the link to the base.

MongoDB shell version v3.4.21
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.21
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
Server has startup warnings: 


I don't know where I went wrong.
If you can help me.

**Comment by parmentf** [comment]
Hmmm... In `host`, I would try `127.0.0.1:27017` directly (skipping the `mongodb://` part, it is never present in [the various configurations](https://github.com/Inist-CNRS/lodex/tree/master/config)).

**Comment by dieubenit** [comment]
Hello,

I do not know, but nothing works for me the connection to the database. 
Is there anyone who has succeeded without facing this kind of problem? 

Because I declared the host of mongo in the docker-compose.yml + config.json

Maybe there is another place to declare it too? 

Thanks for your help.

**Comment by dieubenit** [comment]
Hello, 

Please  someone can give me some ideas to correct the connection errors to the mongodb database. 

````````
Press CTRL+C to stop server
Error [MongoError]: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:16) {
  name: 'MongoError'
}]
    at Pool.<anonymous> (/root/lodex/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:314:20)
    at Connection.<anonymous> (/root/lodex/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:421:26)
    at Connection.emit (events.js:314:20)
    at Socket.<anonymous> (/root/lodex/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:17321) UnhandledPromiseRejectionWarning: Error: L'url de la base mongoDB n'est pas bonne, ou non renseignée.
    at /root/lodex/src/api/services/mongoClient.js:16:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17321) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17321) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

````````

Thanks in advance

**Comment by dieubenit** [comment]
Bonjour, 

Pouvez-vous m'aider sur le point :
### **** https://github.com/Inist-CNRS/lodex/pull/1412 En production lodex ne choisit plus la base Mongo automatiquement et affiche un message d'erreur explicite en cas de non connexion à la base de données ****

J'ai besoin de quelques idées pour relier lodex a ma base de donnée mongodb. 

Merci d'avance.

**Comment by dieubenit** [comment]
Hello,
I've fixed the problem of automatic connection of lodex to the mongodb database.
The application is working in production mode now.

**Comment by parmentf** [comment]
Can the solution interest other persons?

Maybe you can share what you did in order to help other users?

Thanks in advance.

**Comment by dieubenit** [comment]
Solution:

You have to modify the file :

vi src/api/services/mongoCleint.js

export const mongoConnectionString = 'mongodb://mongo:27017/lodex'
