### ISSUE TITLE
Export: last resource is not exported

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#148]
In v5.6.0, I loaded the [films data](https://raw.githubusercontent.com/madec-project/showcase/master/demo_films/repository/films.csv), and, once published, exported it.

I got only 29 lines in my `export.csv`, which should have 30 lines (there are 29 resources in `films.csv`).

`Dracula` is not in the exported data.

**Comment by djhi** [comment]
Just tried myself, the problem is that the last line of movies (Dracula) isn't imported at all.

**Comment by parmentf** [comment]
Oh. Hard to tell when you cannot paginate correctly ;P

**Comment by djhi** [comment]
The fix for the pagination is on its way

**Comment by ThieryMichel** [comment]
Found the cause. The conversion from buffer to stream ignored the last line. A PR to fix it is on its way.
