### ISSUE TITLE
Problem updating lodex

### ISSUE THREAD

**Issue by dieubenit** [Inist-CNRS/lodex#1618]
Hello,
I don't know if someone can help me.
I did an update of lodex 12.23.3 to 12.42.0
But I still have the 12.23.3 version starting, even if the packages.json shows the 12.42.0 version file

**Comment by yannguillemin** [comment]
Sorry @dieubenit , but I have to close this issue because too old. Hoping that this was resolved at the time.
I think you are currently using version 12.49.0.
