### ISSUE TITLE
CSV loaders now loads the file several times

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#186]
Loading the [films](https://github.com/Inist-CNRS/lodex-use-cases/blob/master/films/data.csv), and publishing it results in a 87-resources database!

It's now 3 times the number of resources within the source file.

lodex 6.6.0

**Comment by parmentf** [comment]
Maybe linked to issue #148?

**Comment by djhi** [comment]
Can't reproduce on 6.5.0

**Comment by parmentf** [comment]
OK, I'll check.

**Comment by parmentf** [comment]
Indeed, just after loading, it's OK:
![image](https://cloud.githubusercontent.com/assets/595509/24205358/79b54938-0f1b-11e7-9332-0ef5d875993d.png)

After model import, OK too.

After publishing, still OK.

After exporting, OK.

I can't reproduce either, even in 6.6.0.

I'm still puzzled.

**Comment by touv** [comment]
@parmentf it s linked with this fix https://github.com/touv/node-ezs-basics/commit/0a903d66cc6d9a92fd53106dc993d9a30ec27de6

**Comment by djhi** [comment]
any news on this one ?

**Comment by parmentf** [comment]
It seems to be fixed. Never saw it again.
