### ISSUE TITLE
Align pagination to left

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#189]
Because of the horizontal scrollbar when you have many columns, putting the pagination on the right side can be a pain to use.

![image](https://cloud.githubusercontent.com/assets/595509/24204959/58c1c8f6-0f1a-11e7-86b0-f01e33fc39f4.png)

**Comment by parmentf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As Max, I can't find the pagination when Julia set many columns](https://trello.com/c/ycq5ltMD/181-as-max-i-can-t-find-the-pagination-when-julia-set-many-columns)

**Comment by djhi** [comment]
Should not be necessary anymore with the new fixes on the layout
