### ISSUE TITLE
Erreur Bad gateway sur un precalcul

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1955]
Lien vers la carte :https://trello.com/c/1m1qA6uS/565-erreur-bad-gateway-sur-un-precalcul

Attachements: ![image](https://trello.com/1/cards/65aa90be45a6417f63d65250/attachments/65aa91014173a8d5bc65dbbc/previews/65aa91024173a8d5bc65dc0a/download/image.png)

**Comment by touv** [comment]
Problème  lié à la configuration d'un proxy

**Comment by yannguillemin** [comment]
Le problème n'est plus d'actualité (en tout cas, impossible à reproduire) avec la version 14.0.62 de Lodex.
<img width="804" alt="image" src="https://github.com/user-attachments/assets/c75aefde-c868-4710-831b-bfa0928135c9">
<img width="752" alt="image" src="https://github.com/user-attachments/assets/8763767d-0b71-454c-9179-b069ecd34c25">
