### ISSUE TITLE
[14.0.50] Comportement aléatoire des imports d'enrichissements

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1958]
Des enrichissements, lancés ou pas, sur une instance et enregistrés dans un modèle peuvent se retrouver en colones originelles du dataset et non en enrichissement après import du modèle sur une autre instance. Ils n’ont pas besoins d'être lancés mais ne sont plus non plus modifiables.

Lien vers la carte :https://trello.com/c/gdT8BQyW/623-14050-comportement-al%C3%A9atoire-des-imports-denrichissements

Attachements: ![image](https://trello.com/1/cards/66196d4db94252d1cfdcad67/attachments/66196da9e594bc75801dfdd5/previews/66196daae594bc75801dfe2e/download/image.png)

**Comment by yannguillemin** [comment]
"Issue" expliquée par @AnaelKremer dans la carte Trello originelle. L'import d'enrichissements ne présente pas de caractère aléatoire.
