### ISSUE TITLE
[v14.0.46] front : export depuis page ressource KO (sur tout agents)

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1959]
Lien vers la carte :https://trello.com/c/VIR37ELP/593-v14046-front-export-depuis-page-ressource-ko-sur-tout-agents

Attachements: ![image]()

**Comment by yannguillemin** [comment]
Avec la V14.0.62, l'export des ressources aux formats json et csv et bien fonctionnel.
Il l'est normalement aussi pour le format ris si les ressources sont bien sémantisées au préalable.
