### ISSUE TITLE
[v14.0.40] Administration : suppression de champs composant un autre champs provoque crash page affichage du champ composé

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1960]
J’ai supprimé un champs composant un autre champs (j’ai réussi ! pas pu résister car pas interdit) : BUG : onglet affichage du champs composé = page blanche

Lien vers la carte :https://trello.com/c/rd0R44DG/598-v14040-administration-suppression-de-champs-composant-un-autre-champs-provoque-crash-page-affichage-du-champ-compos%C3%A9

Attachements: ![image]()

**Comment by HeleneCreusot** [comment]
résolu : le champ supprimé est remplacé par le text : "champ manquant" dans l'affichage de la composition du champ composé
