### ISSUE TITLE
Problème avec l'import par liste de DOI

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1961]
**tests le 6 et 7 mars, puis 11 mars** (v14.0.44)

Interrogation OpenAlex via le loader “TXT-liste de DOI” personnalisé ne renvoie aucune info autre que les colonnes uri et lodexStamp (après une 1e réponse presque complète)

test avec unpaywall : ne fonctionne pas

test avec version 14.0.38 : rien ne se déclenche (que ce soit avec provider openalex ou unpaywall)

Lien vers la carte :https://trello.com/c/BK5yu1VI/591-probl%C3%A8me-avec-limport-par-liste-de-doi

**Comment by yannguillemin** [comment]
Tentative de reproduction du bug avec la v14.0.62 : 
- requête fonctionnelle avec "Unpaywall" : 27 colonnes reçues 
- requête fonctionnelle mais renvoie 412 (hors uri, doi et lodexStamp) colonnes dont 149 attribuables à des index de position pour les mots de l'abstract

Rq : bien spécifier "text" dans la liste déroulante "Code source syntax" et mettre un doi par ligne sans séparateur.

![image](https://github.com/user-attachments/assets/e6514dce-7bd5-4caa-b1cf-bd52e30af4f3)
