### ISSUE TITLE
[v14.0.49] Impossibilité de récupérer le résultat d'un précalcul

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1962]
Lorsque l’on veut télécharger les données précalculées ont obtient systèmatiquement en retour un tableau de 10 objets vides

[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]

Lien vers la carte :https://trello.com/c/h7vkwICr/620-v14049-impossibilit%C3%A9-de-r%C3%A9cup%C3%A9rer-les-donn%C3%A9es-pr%C3%A9-calcul%C3%A9es

**Comment by touv** [comment]
il est également possible de voir s'afficher "null" mais si on attend un peu les données finissent pas apparaître... je ne sais pas si c'est le même problème

**Comment by touv** [comment]
Si les données s'affichent 
![image](https://github.com/user-attachments/assets/596f1152-1014-4114-b4df-b28a17544002)
mais que le téléchargement est vide 

c'est que le web service ne retourne pas un champ value  .

Lodex filtre l'export avec les champs id et value https://github.com/Inist-CNRS/lodex/blob/master/src/api/models/precomputed.js#L96

**Comment by touv** [comment]
@parmentf les webservices asynchrones sont-ils standardisés comme les webservices synchrones avec des object en retour de type { id, value }
