### ISSUE TITLE
[v14.0.49] connecté en admin : accès au paramétrage d'un élément côté front renvoie sur la page de connexion admin

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1963]
… alors qu’on est donc déjà connecté

Lien vers la carte :https://trello.com/c/Aaz2G4Fl/618-v14049-connect%C3%A9-en-admin-acc%C3%A8s-au-param%C3%A9trage-dun-%C3%A9l%C3%A9ment-c%C3%B4t%C3%A9-front-renvoie-sur-la-page-de-connexion-admin

**Comment by HeleneCreusot** [comment]
ce fonctionnement est probablement lié au dev sur ezmaster
