### ISSUE TITLE
[14.0.32] Pas de message d'erreur sur type de données erroné pour précalcul

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1964]
- tree-segment sur un résumé => aucun message d’erreur et pas de fin du précalcul qui reste bloqué à l'étape “**Waiting for response data**”
- graph-segment sur un objet contenant des tableaux de chaînes de caractères => aucun message d’erreur et pas de fin du précalcul qui reste bloqué à l'étape “**Waiting for response data**”

r

Lien vers la carte :https://trello.com/c/sf2OE6xM/536-14032-pas-de-message-derreur-sur-type-de-donn%C3%A9es-erron%C3%A9-pour-pr%C3%A9calcul

Attachements: ![image]()

**Comment by yannguillemin** [comment]
La V14.0.62 affiche maintenant un message d'erreur pour le 1er exemple et arrête le pré-calcul.
<img width="646" alt="image" src="https://github.com/user-attachments/assets/a0446b92-2896-49f1-b932-cd38c9a1a40e">
Toujours avec la V14.0.62, le deuxième exemple fonctionne : 
<img width="798" alt="image" src="https://github.com/user-attachments/assets/2e7f7726-966d-4a56-9c7a-c1fb51a89305">
<img width="761" alt="image" src="https://github.com/user-attachments/assets/59d27a6a-bb86-4fe4-b3fd-5c6e13fd0458">
