### ISSUE TITLE
Echec de la sauvegarde après modification d'une donnée sous forme d'une équation

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1965]
version: 12.55.2

Modification d’une donnée dans la revue de sommaire

exemple

1- Recherche de la revue “**Zeitschrift für Angewandte Mathematik und Physik (ZAMP)”**  la couverture renvoie sur une autre revue **“Biotechnology and Bioprocess Engineering”**

2- Je vais dans le back office pour vérifier et ou corriger la requête à l’api

3-Effectivement mauvaise requête sur un autre titre : vide l'équation et remet la bonne qui correspond au titre recherché

**corpusName:"springer-journals" AND (host.issn:"0044-2275" OR host.eissn:"1420-9039" OR host.title.raw:"Zeitschrift für Angewandte Mathematik und Physik (ZAMP)")**

4- Je sauvegarde et tant que je reste dans le back office la donnée modifiée est bien sauvegardée.

5- Je retourne dans le front. Je vérifie la sauvegarde de la donnée modifiée mais la recherche me retrouve l’ancienne donnée “Biotechnology and Bioprocess Engineering”\*\*

6- Je retourne dans le back office et l’ancienne donnée est réapparue avec la mauvaise équation : **corpusName:"springer-journals" AND (host.issn:"1226-8372" OR host.eissn:"1976-3816" OR host.title.raw:"Biotechnology and Bioprocess Engineering")**

7- Rien n’a été sauvegardé malgré le message : sauvegarde

Lien vers la carte :https://trello.com/c/ByIE2utM/393-echec-de-la-sauvegarde-apr%C3%A8s-modification-dune-donn%C3%A9e-sous-forme-dune-%C3%A9quation

Attachements: ![image]()

**Comment by yannguillemin** [comment]
Après analyse de la carte Trello associée à cette "issue", il s'avère effectivement que :
- la modification d'une donnée dans la partie "DATA" est bien effective après sauvegarde
- pour que cette modification soit visible dans l'onglet "Search" de l'instance en mode consultation, il faut au préalable republier les données pour observer la modification
Ce process, bien qu'a priori fastidieux, est en fait bien pratique surtout dans le cas de la manipulation de corpus volumineux car une prise en compte de la modification en temps réel entre la "vue" et le "modèle" nécessiterait de republier les données à chaque modification et impliquerait des temps chargements multiples et longs (la MAJ de la "vue" recharge le dataset en entier).
![image](https://github.com/user-attachments/assets/e628218f-972a-4f99-8a96-9777966a8e3e)
