### ISSUE TITLE
Import fichier tar.gz : 1 ligne vide ajoutée

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1966]
Lien vers la carte :https://trello.com/c/4XYqeux0/595-import-fichier-targz-1-ligne-vide-ajout%C3%A9e

Attachements: ![image]()

**Comment by yannguillemin** [comment]
Tentative de reproduction du bug sur la v14.0.62 avec une requête ISTEX au format tar.gz effectuée le 19/09/24 :
import des données réalisé sans problème, aucune ligne vide détectée.
