### ISSUE TITLE
DOI doublons : import possible !

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1967]
Lors de l’import avec un loader paramétré de telle sorte que les DOI soient choisis, comme uri des DOI doublons n’ont pas été détectés.

En revanche, au moment de la publication, des messages d’erreur sont apparus les signalant

Lien vers la carte :https://trello.com/c/eaDM5QuF/603-doi-doublons-import-possible

Attachements: ![image]()

**Comment by yannguillemin** [comment]
Reproduction du bug sur la v14.0.62 avec import des données du fichier en PJ de la carte Trello en utilisant le loader "TXT  - from list of DOI identifiers" qui utilise le DOI pour créer l'uri : on a une liste de 27 DOIs dont 3 doublons et on obtient 24 lignes chargées. En revanche on obtient bien un message d'erreur pour un DOI (10.9714/psac.2021.23.3.037), mais celui-ci ne fait pas parti d'un doublon.
On obtient bien 27 lignes si on charge le csv tel quel, la création de l'uri n'étant pas basé sur les DOIs.
De plus, il faudrait clarifier l'expression du problème car le titre indique que l'import de DOIs doublons est possible (oui quand l'uri créé ne se base pas dessus), mais la description du problème dans la carte Trello indique que des DOIs doublons ne sont pas détectés lorsque la création de l'uri se base dessus (ce qui correspond au comportement attendu).

**Comment by yannguillemin** [comment]
Je clôture cette issue avec les précisions suivantes :
- les URIs sont uniques par définition (analogues à des clés primaires), ainsi l'import de DOIs doublons est impossible si ceux-ci sont utilisés pour créer les URIs
- l'import de DOIs doublons est possible si les URIs sont créées autrement (à partir d'identifiants uniques : uids par ex)
- le fichier en PJ de la carte Trello a été utilisé pour reproduire le bug, mais aucun message d'erreur n'a pu être observé
