### ISSUE TITLE
Problème chargement de fichier sur Firefox

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1969]
Sur Firefox en versions 12.55.4 et 14.0.9-alpha (instance 3)

Quand je charge le dataset “systématique-végétale” (569 Mo) exporté de data.istex en jsonl, j’obtiens le message d’erreur suivant dans la console de développement :

```
Firefox ne peut établir de connexion avec le serveur à l’adresse ws://testsab-multi-3.lodex-dev.inist.fr/socket.io/?EIO=4&transport=websocket&sid=go3c6xxdcd2kkso1AABZ. index.js:610:361354
Uncaught (in promise)
error { target: FileReader, isTrusted: true, lengthComputable: true, loaded: 582763280, total: 582763280, srcElement: FileReader, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, … }
```

La roue “inspection du fichier” tourne indéfiniment

En revanche, aucun problème pour charger mon fichier en le faisant à partir de Chrome.

Lien vers la carte :https://trello.com/c/O249qpNY/441-probl%C3%A8me-chargement-de-fichier-sur-firefox

Attachements: ![image]()

**Comment by yannguillemin** [comment]
Je clôture cette issue car le même problème est rapportée dans la suivante : #1953.
