### ISSUE TITLE
Perte de données à l'export du .csv d'une instance

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1970]
Dans mon cas :

- Après avoir mis au point un fichier csv avec des données que l’on souhaite faire apparaitre,  j’importe mes données => instance parfaite
- Mais si j’exporte mon jeu de données en .csv  2 champs de données (crées uniquement pour les faire apparaitre dans les champs de syndication de recherche : premier détail de la ressource et second détail de la ressource) disparaissent (Des1 et Des2)

Lien vers la carte :https://trello.com/c/WArbEmqg/399-perte-de-donn%C3%A9es-%C3%A0-lexport-du-csv-dune-instance

Attachements: ![image]()

**Comment by yannguillemin** [comment]
L'export csv à partir de l'onglet "Search" se base sur les ressources, et problème venait du fait que ces deux colonnes avaient été utilisées pour créer deux ressources avec le même nom ("Détail du bouquet acquis"). Si j'attribue des noms différents aux ressources créées à partir des colonnes "Des1" et "Des2", c'est à dire "Détail du bouquet acquis1" et "Détail du bouquet acquis 2"), on les retrouve bien dans l'export final (cf. PJ)
[export (5).csv](https://github.com/user-attachments/files/17095774/export.5.csv)
