### ISSUE TITLE
Annulation de l'import impossible (en cas de blocage)

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1973]
Test d’import avec jeu de données **dataset_2021-10-14-syst-anim-complet.json et loader JSON-adapté à Lodex**

l'import tourne dans le vide et reste bloqué à la phase de la sauvegarde du jeu de données. L'annulation de l’import ne fonctionne pas ! Et il n'y a pas de possibilité d'effacer les taches de fond. (voir image annul-import.png et video loader-json-adapted-lodex-syst-anim.mp4).

Seule possibilité : stopper l’instance et la redémarrer.

Data : [https://github.com/Inist-CNRS/lodex-use-cases/tree/master/systematique-animale](https://github.com/Inist-CNRS/lodex-use-cases/tree/master/systematique-animale "smartCard-inline")

NB : Avec le loader “JSon-avec un tableau”, message d’erreur lors du chargement des données signalant un fichier trop volumineux. Pourtant des fichiers plus volumineux ont déjà été importés sans problème. (voir image jointe)

Lien vers la carte :https://trello.com/c/ILybLaqE/286-annulation-de-limport-impossible-en-cas-de-blocage

Attachements: ![image]()

**Comment by touv** [comment]
L'application ne se bloque plus depuis la version https://github.com/Inist-CNRS/lodex/releases/tag/v14.0.57
