### ISSUE TITLE
[v14.0.46] front : graphiques zoom par souris KO (sur tout agents)

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1974]
mais le plein écran fonctionne : merci Pierre !!

Lien vers la carte :https://trello.com/c/wN2HDlsU/609-v14046-front-graphiques-zoom-par-souris-ko-sur-tout-agents

Attachements: ![image]()

**Comment by yannguillemin** [comment]
Sur la V14.0.62, le zoom fonctionne bien pour les graphiques zoomables (flow-maps et networks).
