### ISSUE TITLE
[v14.0.50] thèmes inist& istex et sémantisation

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1976]
Quand un modèle contient des données de sémantisation, l’affichage n'est pas complètement optimisé

- thème istex : les infos de sémantisation d’un champ sont affichés à droite du champ => si plusieurs champs alignés, la sémantisation d’un champ est collé au libellé du champ contigu
- thème inist : en page d’accueil, pour les titres et sous-titres, la sémantisation est affichée au-dessus du champ concerné

Lien vers la carte :https://trello.com/c/GTpWXL8O/624-v14050-th%C3%A8mes-inist-istex-et-s%C3%A9mantisation

Attachements: ![image]()

**Comment by HeleneCreusot** [comment]
après analyse, cette mise en page vient des styles css générés par le code Lodex.
sur le container -> .property_label_container div
display: flex;
  **justify-content: flex-end;**
  align-items: center;

sur l'élément -> span.property_scheme
élément {
  font-size: 0.75rem;
  **align-self: flex-end;**
}

quel est l'usage, autre que la lecture informative, de cet élément ?
Cet élément est-il lié au label ou à la donnée ?
Quelle serait la mise en page idéale ?

**Comment by HeleneCreusot** [comment]
suite à lundi : temps d'échange lodex : 
l'annotation sémantique est attachée au label (étiquette en admin)
dans un premier temps, @AlasDiablo va amender la css lodex native pour espacer les champs lodex => cible css .property.
#TODO : les .property sont contenus dans une div sans class avec style=display: flex, ...

il faut ajouter gap: 2%;

**Comment by HeleneCreusot** [comment]
@AlasDiablo pourrais-tu en profiter pour changer color du nom interne des champs du front/admin/affichage/page ?
![image](https://github.com/Inist-CNRS/lodex/assets/122360177/f2a19507-c85c-458e-b02d-0b1aa9d8c4fb)

--toastify-text-color-light ou #757575 au lieu de rgb(224, 224, 224)

redis-moi si c'est possible car sinon, je fais une issue
