### ISSUE TITLE
[14.0.40] Format "lodex-field" ne fonctionne plus

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1977]
Depuis la version lodex 14.0.40, le format lodex-field ne permet plus d’afficher les informations choisies.

Problèmes pour les ressources des jeux de données publiés sur data.istex :

- corpus scientifiques : champs “langue de publication” et “éditeur”
- référentiels : exemple de loaded-corpus (jeu de données et modèle joints à cette carte) => plus d’affichage des données pour le sous-champ “information sur l'éditeur”

Lien vers la carte :https://trello.com/c/xc9Yhpep/628-14040-format-lodex-field-ne-fonctionne-plus

Attachements: ![image]()

**Comment by touv** [comment]
bloque la migration en lodex 14 pour data.istex.fr
