### ISSUE TITLE
nom interne = class : la class interne disparait de l'élément lorsqu’il est dans un autre élément (annotation ou composant).

### ISSUE THREAD

**Issue by inistcnrs** [Inist-CNRS/lodex#1987]
la class interne disparait de l'élément lorsqu’il est dans un autre élément (annotation ou composant).

pose problème pour la généricité du theme.

exemple : je ne peux pas cibler le compteur dans la sidebar en page d’accueil du futur tools explorer.

remarque : je le cible actuellement par sa position

Lien vers la carte :https://trello.com/c/UYxwoCv7/613-nom-interne-class-la-class-interne-disparait-de-l%C3%A9l%C3%A9ment-lorsquil-est-dans-un-autre-%C3%A9l%C3%A9ment-annotation-ou-composant

Attachements: ![image]()

**Comment by touv** [comment]
![image](https://github.com/Inist-CNRS/lodex/assets/15609/5f42a363-0d4a-44a8-87a5-fa2d525283a4)

**Comment by touv** [comment]
cf. https://github.com/Inist-CNRS/lodex/blob/0c0c9ae02fb16b31f3ed8a6a6d3b239243fd877f/src/app/js/public/Property/CompositeProperty.js#L37
