### ISSUE TITLE
Démarrage en production très lent

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#1989]
Au lancement du container, le site met plusieurs minutes à s'afficher ce qui est confirmé par les logs 
![image](https://github.com/Inist-CNRS/lodex/assets/15609/0ad6db12-a366-4e8f-9849-936791bfe5e3)

avec plus de 4 minutes !

**Comment by touv** [comment]
https://github.com/Inist-CNRS/lodex/blob/4be7471892a2a6b3fd9f7a16a936452b8236d19d/src/api/models/themes.js#L139

**Comment by parmentf** [comment]
I think this is closed by error: adding profiler logs won't fix the slow startup.
