### ISSUE TITLE
affichage d'un graphique simple en erreur

### ISSUE THREAD

**Issue by cguele** [Inist-CNRS/lodex#1991]
Avec routine distinct-by
Si nombre de champs max = 200, graphique en erreur
<img width="811" alt="Annotation 2024-04-26 111439" src="https://github.com/Inist-CNRS/lodex/assets/108339154/48a848fd-905d-4a79-bde7-5e4d037b72a3">

MAIS graphique s'affiche si on sélectionne les champs concernés dans les facettes à gauche
<img width="842" alt="Annotation 2024-04-26 111546" src="https://github.com/Inist-CNRS/lodex/assets/108339154/693eede6-2395-4f48-8e6b-c0cdb6ffc4c0">
Le nombre de facettes sélectionnables est de 16, dès que j'en sélectionne une de plus le graphique se met à nouveau en erreur
<img width="837" alt="Annotation 2024-04-26 111705" src="https://github.com/Inist-CNRS/lodex/assets/108339154/a9d76583-19dd-4ded-a75d-c5287d7f9326">

SI nb de champs max <= 16, graphique s'affiche
<img width="783" alt="Annotation 2024-04-26 110854" src="https://github.com/Inist-CNRS/lodex/assets/108339154/76c8e616-f89a-450a-baaa-f079ad636562">

**Comment by touv** [comment]
fix #1990

**Comment by touv** [comment]
see #1986
