### ISSUE TITLE
page resource : étendre la fonctionnalite  d'un champ 'nom interne = class css' sur le premier champ du modèle

### ISSUE THREAD

**Issue by HeleneCreusot** [Inist-CNRS/lodex#2000]
@touv  : Le premier champs du modèle 'resource' est affecté dans la div.header-resource-section. Son nom interne n'est pas repris pour devenir une class css. Donc actuellement, cette possibilité ne s'applique que sur le bloc html div.main-resource-section. 

structure html resource : div.resource > span.detail > div.header-resource-section + div.main-resource-section.

étendre sur l'ensemble des .property, toutes contenues dans span.detail.

**Comment by touv** [comment]
Je pense que ce problème a été traité dans cette issue #1987

**Comment by touv** [comment]
et donc testable dans la version 14.0.51, 
@HeleneCreusot peux-tu confirmer ?

**Comment by HeleneCreusot** [comment]
> et donc testable dans la version 14.0.51, @HeleneCreusot peux-tu confirmer ?

@touv : cela concerne la première property du modèle non traitée

**Comment by HeleneCreusot** [comment]
![image](https://github.com/Inist-CNRS/lodex/assets/122360177/53fbf997-0ec3-43f0-aa8d-d3398c762fd2)

**Comment by HeleneCreusot** [comment]
![image](https://github.com/Inist-CNRS/lodex/assets/122360177/9327c708-25d6-4419-9358-5afd7f6f27af)
