### ISSUE TITLE
[v14.0.53] chevauchement de champ dans firefox

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2040]
dans firefox
![image](https://github.com/Inist-CNRS/lodex/assets/15609/1f98e955-8389-43d1-b315-46721ffe7079)
dans chrome
![image](https://github.com/Inist-CNRS/lodex/assets/15609/afdb4ba3-be09-4e3b-89c1-ffb373ab7649)

**Comment by HeleneCreusot** [comment]
@touv : pb  avec firefox -> non prise en compte par un container du gap height en % sur ses éléments
résolution (vu avec @AlasDiablo) -> concerne lodex code  espacement entre les .property : mettre gap: 1wv au lieu de 1%
