### ISSUE TITLE
 [version 14.0.59] graphe réseau incomplet à l'affichage et impossible de le déplacer

### ISSUE THREAD

**Issue by Bonvallot** [Inist-CNRS/lodex#2050]
![image](https://github.com/Inist-CNRS/lodex/assets/35224723/693437a7-19d9-4eb8-b165-7543eb6ad03a)
Le réseau reste en haut à gauche et une partie du réseau est invisible
Impossible de le réduire avec la roulette et de le déplacer

**Comment by touv** [comment]
est-ce le même problème qu'ici https://github.com/Inist-CNRS/lodex/issues/2048

si le pb est toujours présent dans la version 14.0.55 alors il est différent ... 

Est-ce possible de vérifier ?

**Comment by Bonvallot** [comment]
ce n'est pas le même problème
il s'agit ici de l'affichage des réseaux (et non des graphes à bulles)

**Comment by HeleneCreusot** [comment]
@Bonvallot avec quel theme stp ?

**Comment by Bonvallot** [comment]
@HeleneCreusot avec le thème INIST (restreint) (thème obsolète). Tous les thèmes sont obsolètes, que cela signifie-t-il ?

**Comment by HeleneCreusot** [comment]
Bonjour,
il semblerait que la version 14.0.57 corrige le bug, @Bonvallot peux-tu vérifier ?

c'est peut être cette PR :  https://github.com/Inist-CNRS/lodex/pull/2083

**Comment by HeleneCreusot** [comment]
@Bonvallot @AlasDiablo 
version 14.0.59 : bug non résolut

problème de **positionnement** (Graphique Réseaux) et/ou de **zoom souris** (Graphes à bulles)  : 

**réseau des instituts**
http://192.168.31.29:49214/instance/testrgraph/graph/snIU
- valeur arbitraire : /api/run/graph-by/eENv
- affichage format : Graphique - Réseaux

**catégorie wos**
http://192.168.31.29:49214/instance/lodexcouleurs/graph/n6zH  
- valeur arbitraire : /api/run/tree-by/aNG3
- affichage format : Graphique - Réseaux

**Mots-clés détectés**
http://192.168.31.29:49213/instance/lodexcouleurs/graph/a1eL
- valeur arbitraire : /api/run/distinct-by/S6KJ
- affichage format : Graphique - Graphe à bulles
=> pas de zoom souris possible pour les graphes à bulles

**Collaborations auteurs français**
http://192.168.31.29:49215/instance/semantisation/graph/V9M0
- valeur arbitraire : /api/run/cross-by/a3R9/a3R9
- affichage format : Graphique - Réseaux

@touv 
~~et tout fonctionne pour d'autres~~ : NON celui là aussi est buggé

**réseau des laboratoires**
http://192.168.31.29:49214/instance/testrgraph/graph/XVpT  
- valeur arbitraire : /api/run/graph-by/vmD1
- format : Graphique - Réseaux

Tester ce graph avec les filtres des facettes révèle qu'il y a le même dysfonctionnement avec la souris : problème de déplacement du graph y compris en mode zoom

**Comment by touv** [comment]
peut-être lié à https://github.com/Inist-CNRS/lodex/blob/master/src/app/js/formats/utils/components/ZoomableFormat.js

**Comment by HeleneCreusot** [comment]
> peut-être lié à https://github.com/Inist-CNRS/lodex/blob/master/src/app/js/formats/utils/components/ZoomableFormat.js

je ne pense pas, il s'agit du zoom souris pour les bubblePlot. Je vais l'indiquer dans mon précédent message.

@AlasDiablo est-ce qu'il faudrait ajouter  dans https://github.com/Inist-CNRS/lodex/blob/theme-istex-for-istex-corpus/src/app/js/formats/chart/bubbleChart/BubbleView.js  

`  import MouseIcon from '../../utils/components/MouseIcon'; `

 
comme dans https://github.com/Inist-CNRS/lodex/blob/theme-istex-for-istex-corpus/src/app/js/formats/chart/network/NetworkView.js ligne 18 ?

...si c'est cela qui permet le zoom souris

**qu'en penses-tu @touv ?**

**Comment by HeleneCreusot** [comment]
@touv, @Bonvallot @AlasDiablo : le problème apparait dans la [v14.0.46](https://github.com/Inist-CNRS/lodex/releases/tag/v14.0.46)

@AlasDiablo peut-être dans le commit [aspect-ratio](https://github.com/Inist-CNRS/lodex/pull/1923/commits/ffce625b70b9709ca5ed52eea0c1347d3f7da4d8) ?

**Comment by HeleneCreusot** [comment]
@touv, @Bonvallot @AlasDiablo : le problème apparait dans la v14.0.46.
