### ISSUE TITLE
[14.0.55] impossible de configurer un thème depuis l'espace de configuration

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2058]
Maintenant, il est théoriquement possible de modifier les variables associées à un thème depuis l'interface de configuration. Problème changer les variables ne change rien.

[Capture vidéo 2024-06-21 15:49:41.webm](https://github.com/Inist-CNRS/lodex/assets/15609/e55300cd-4c32-436e-ae82-c946446f8220)

**Comment by HeleneCreusot** [comment]
@touv bonjour, la vidéo ne fonctionne pas. quel theme et quelles données sont concernés ?
à+

**Comment by touv** [comment]
j'ai changé le format de vidéo de mp4 à webm, elle sera lisible sur firefox et chrome

**Comment by HeleneCreusot** [comment]
oui, c'est normal, le theme istex n'est pas à jour pour ldx55 ; la mise à jour ejs sera faite par toi (ou moi dans une nouvelle branche selon ton choix) lors du merge de https://github.com/Inist-CNRS/lodex/pull/2038
