### ISSUE TITLE
Bug changement des couleurs pour le treemap

### ISSUE THREAD

**Issue by yannguillemin** [Inist-CNRS/lodex#2062]
Il est possible de changer les couleurs du treemap et ses dimensions en passant par le mode avancé.
Néanmoins, ce type de customisation en passant par l'interface graphique provoque un bug lorsque l'on souhaite changer le set de couleurs (renvoi vers une page vide et remise à zéro des modifications) et le choix du rapport d'aspect est inopérant.

**Comment by touv** [comment]
@AlasDiablo aurais-tu une idée du problème ?
