### ISSUE TITLE
Possibilité de réaliser un TreeMap sans notion de hiérarchie

### ISSUE THREAD

**Issue by AnaelKremer** [Inist-CNRS/lodex#2075]
Le graphique TreeMap a été ajouté récemment dans le catalogue, mais on ne peut l'utiliser qu'avec des données décrivant une hiérarchie.

Serait-il possible de développer un autre genre de TreeMap qui s'appuierait sur une simple paire id / value au lieu de source / target / weight ?

L'idée est simplement de calculer la proportion de chaque id / value par rapport au total de value et de lui attribuer une dimension proportionnelle au rectangle global.

**Comment by yannguillemin** [comment]
Effectivement, ce serait pratique. En attendant, il est possible de contourner cela en associant deux champs dont le premier est une valeur constante et en choisissant ensuite de ne pas afficher la source dans le tool-tip. Puis il faut modifier le script vega-lite pour associer les couleurs aux "leaves", affecter "tree" au lieu de "nodes" au champ data dans "marks". Un exemple sur l'instance de test : (https://lodex-dev.inist.fr/instance/default/graph/UHbq).
