### ISSUE TITLE
L'arret d'un chargement trop long provoque le blocage de l'application

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2077]
Cliquer sur le croix en haut droite pour arrêter un chargement en cours, provoque le blocage complet de l'application.

Tous les chargements ne sont pas concernés, mais le problème semble se reproduire avec des chargements par requête

**Comment by HeleneCreusot** [comment]
@touv est ce équivalent à : 
[Annulation de l'import impossible (en cas de blocage)]( https://github.com/Inist-CNRS/lodex/issues/1973)

et 
 [[v14] Annulation import données : pas de notification et processus se poursuit #1968 ](https://github.com/Inist-CNRS/lodex/issues/1968)
?

**Comment by touv** [comment]
> @touv est ce équivalent à : [Annulation de l'import impossible (en cas de blocage)](https://github.com/Inist-CNRS/lodex/issues/1973)
> 
> et [[v14] Annulation import données : pas de notification et processus se poursuit #1968 ](https://github.com/Inist-CNRS/lodex/issues/1968) ?

oui très probablement

**Comment by touv** [comment]
L'application ne se bloque plus depuis la version https://github.com/Inist-CNRS/lodex/releases/tag/v14.0.57
