### ISSUE TITLE
Ajouter une documentation pour la personnalisation des variable de thème

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2092]
Dans la page https://github.com/Inist-CNRS/lodex/blob/master/src/app/custom/themes/istex/Readme.md

On voit bien comme utiliser les noms de classe interne. Par contre on ne sait pas comment changer le titre et le sous titre.

il faudrait indiquer le nom des variables disponibles  et  ou les mettre dans la configuration de l'instance. 

Pour information voici un exemple qui fonctionne : 
![image](https://github.com/Inist-CNRS/lodex/assets/15609/287d1457-b25a-4f62-b249-d536ad446430)

**Comment by HeleneCreusot** [comment]
@touv demande faite auprès de @AlasDiablo d'enrichir la config côté front avec les variables déclarées dans lodex-theme.json d'un thème.
