### ISSUE TITLE
[14.0.56] Thème INIST - Présence de "Etudes" dans l'entête

### ISSUE THREAD

**Issue by nantonot** [Inist-CNRS/lodex#2097]
Présence de "Etudes" dans l'entête : est-il possible d'enlever cette mention ?
![image](https://github.com/user-attachments/assets/b13a3c92-e845-4916-af01-f00fe94ed15d)

De plus, quand on clique dessus, le lien renvoie vers la page de connexion (instance/default), alors qu'on est connecté (en tant que admin ou user (ce qui est problématique))
![image](https://github.com/user-attachments/assets/59181901-8e76-4ad1-a7da-b1860e634a1f)

**Comment by HeleneCreusot** [comment]
@nantonot ok, on a bossé en même temps (cf. #2098)

je corrige le lien pour qu'il pointe vers l'accueil

Pour le titre, il peut être optionnel mais c'est à voir avec Patricia et/ou @touv
