### ISSUE TITLE
[14.0.56] Fenêtre popup - serait-il possible de l'élargir ?

### ISSUE THREAD

**Issue by nantonot** [Inist-CNRS/lodex#2100]
Dans la 14.0.x de Lodex, il est désormais possible de créer des fenêtres popup pour y mettre des données explicatives. Serait-il possible d'élargir la fenêtre pour une meilleure facilité de lecture ?
![image](https://github.com/user-attachments/assets/44f492dc-a68c-42d0-b96a-5a0dcd4e6e78)

**Comment by parmentf** [comment]
Un typographe te dirait qu'un paragraphe est plus facile à lire lorsqu'il est coupé en plusieurs lignes, et que chaque ligne n'a pas la même longueur (l'œil retrouve plus facilement la ligne sur laquelle il se trouvait).

Donc augmenter la largeur d'un paragraphe n'améliore pas forcément sa lisibilité.

**Comment by AlasDiablo** [comment]
@parmentf Une taille plus proche du A4 serais pas mieux ?

![Screenshot_20240718_105609](https://github.com/user-attachments/assets/c8f6d27c-bffd-495e-ad4e-249b7a3f5034)

**Comment by HeleneCreusot** [comment]
@parmentf c'est exact. @AlasDiablo pour moi c'est ok. @nantonot , qu'en penses-tu ?

**Comment by nantonot** [comment]
@parmentf @AlasDiablo @HeleneCreusot ok
mettre la fenêtre en A4 ou en plein écran avec une petite croix pour la refermer ?

**Comment by HeleneCreusot** [comment]
> ok mettre la fenêtre en A4 ou en plein écran avec une petite croix pour la refermer ?
@nantonot 
la croix est déjà présente, pas de souci.

il s'agit d'une largeur maximum qui maintient le confort de lecture donc l'ergonomie. Lire un texte sur un écran de largeur 1200px n'est pas un usage commun et déroute la plupart des lecteurs (cf. ce qu'écrit @parmentf )
Cette largeur est maintenue sur tous les écrans dont la largeur sont sup ou = à 800px

donc je propose de de tester cette largeur, qu'en dis-tu ?

**Comment by nantonot** [comment]
@HeleneCreusot ok
