### ISSUE TITLE
[14.0.57 & 56] Les graphiques hiérarchiques utilisant tree-by ne fonctionnent plus

### ISSUE THREAD

**Issue by AnaelKremer** [Inist-CNRS/lodex#2111]
Les arbres hiérarchiques ne fonctionnent plus dès lors que l'on dépasse quelques dizaines de valeurs à calculer.

Le graphique se charge puis la page crash, s'il y avait d'autres graphiques sur la même page ils disparaissent également.

Après plusieurs tests, des corpus de 40 ou 70 notices permettent d'afficher l'arbre mais avant 200 le bug apparaît déjà.

On peut voir ce comportement sur ce lodex par exemple https://lodex-dev.inist.fr/instance/findapc/ en voulant consulter le graphique "classification OpenAlex" qui comprend 5 graphiques dont 1 arbre hiérarchique.

Les logs : 
[logs_tree-by.txt](https://github.com/user-attachments/files/16349954/logs_tree-by.txt)

**Comment by touv** [comment]
L'erreur semble venir de MongoDB : 
```
MongoServerError: MapReduce internal error :: caused by :: indexes of target collection instance-globale_findapc.mp_0b1a18a0b73b782359e0ef6cdf7538a0623aa996572b780678c486ec7f5326ca changed during processing
```

**Comment by AnaelKremer** [comment]
là j'arrive à l'afficher sur un jeu de 559 docs, ce n'est donc peut être pas forcément lié à la taille du corpus...

**Comment by AnaelKremer** [comment]
Message d'erreur du navigateur (testé sous chrome et firefox)

WARN Dropping "fit-y" because spec has discrete height. 2 index.js:102:258082
Uncaught TypeError: this.divContainer.current is null
    value http://192.168.31.238:49351/index.js:155
    value http://192.168.31.238:49351/index.js:155

**Comment by touv** [comment]
https://github.com/Inist-CNRS/lodex/blob/c4e36de6bffa72ef9793b5ee2e193bfb4d1b4aff/src/app/js/formats/chart/hierarchy/Hierarchy.js#L117

**Comment by touv** [comment]
https://github.com/Inist-CNRS/lodex/blob/c4e36de6bffa72ef9793b5ee2e193bfb4d1b4aff/src/app/js/formats/chart/hierarchy/Hierarchy.js#L165

**Comment by touv** [comment]
Dans l'exemple findapc, si on corrige le bug de la page blanche, à priori on découvre une polyhiérarchie : 
```

{
    "source": "2 - Biochemistry, Genetics and Molecular Biology",
    "target": "3 - Genetics",
    "weight": 1
},
{
    "source": "2 - Medicine",
    "target": "3 - Genetics",
    "weight": 2
},
 
 ```
 
 je ne sais pas si le graphique peut gérer ce type de cas

**Comment by AnaelKremer** [comment]
Oui c'est pas top de mettre les mêmes termes sur différentes branches...
