### ISSUE TITLE
champ compose : suprimer la bordure et le retrait par defaut

### ISSUE THREAD

**Issue by HeleneCreusot** [Inist-CNRS/lodex#2123]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire**  
la composition de champ à la même présentation que les champ annotés : 
- marge à gauche du bloc 
- bordure à gauche
- marge interne à gauche

**Décrivez la solution que vous souhaitez**  
pas de bordure ni de retrait pour un champ composé qui peut être une ligne, un paragraphe... et qui implique une structuration du texte

**Décrivez les alternatives que vous avez envisagées**  
supprimer la bordure et le padding dans le fichier https://github.com/Inist-CNRS/lodex/blob/master/src/app/js/public/Property/CompositeProperty.js

**Contexte supplémentaire**  
![image](https://github.com/user-attachments/assets/a9f6afbc-ea5c-48d9-bf84-833bb21edc84).

**Comment by HeleneCreusot** [comment]
@touv  comme convenu, voici la description de la modification que je propose pour l'affichage des champs composants un autre champ.
j'attends un feu vert de l'équipe pour ouvrir une branche, ok ?

**Comment by touv** [comment]
@HeleneCreusot tu peux faire la PR associée
