### ISSUE TITLE
Recherche impossible avec le thème "VOID"

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2127]
Avec le thème "void", la recherche provoque une page blanche.
[Screencast_00007.webm](https://github.com/user-attachments/assets/0ebaea5a-b08b-48f0-9e43-8849adc2569a)

**Comment by KingJuliann** [comment]
Quand on recherche, un item, puis qu'on clique sur page précédente puis sur une facette, toute la page disparaît et le retour en arrière ne fonctionne plus.

**Comment by HeleneCreusot** [comment]
@touv le bug apparait à partir de la [v14.0.52](https://github.com/Inist-CNRS/lodex/releases/tag/v14.0.52)

console
![image](https://github.com/user-attachments/assets/940666f4-88b7-48a5-9425-58d54fd6af17)


![consoleWarning](https://github.com/user-attachments/assets/c2a9cdcb-9203-49fa-9cc6-0b0fce237757)

**Comment by HeleneCreusot** [comment]
@touv la v14.0.52 intègre les commits de restructuration des thèmes

 https://github.com/Inist-CNRS/lodex/pull/1999
