### ISSUE TITLE
(0,5) [14.0.57]Filtre par facette ne fonctionne pas quand on ne se trouve pas sur la première partie de la liste

### ISSUE THREAD

**Issue by Bonvallot** [Inist-CNRS/lodex#2130]
**Décrire le bogue**
Quand on recherche un terme dans une facette à partir de la deuxième liste de mots, la recherche ne fonctionne pas

**Reproduire**
Étapes pour reproduire le comportement :

1. Allez à ['...'](http://192.168.31.148:49268/instance/anftdm-biodiversite/)
2. Cliquez sur Recherche
3. Faites défiler l'écran jusqu'à la facette Pays nettoyés ou paysCorr_addressSplit
4. Cliquez sur la flèche pour accéder à la suite de la liste des termes, saisir France, aucune valeur n'apparaît

**Comportement attendu**
Pouvoir faire une recherche dans une facette, même quand on ne se trouve pas sur la première partie de la liste des termes

**Environnement (veuillez compléter les informations suivantes) :**

- Navigateur [Mozilla]

- Version de LODEX [14.0.57]

**Comment by HeleneCreusot** [comment]
@Bonvallot oui effectivement,
 j'ai l'impression que c'est le même pb que  Admin : Filtre sur des pages différentes de la première page n'affiche pas de résultat #2074 

il faut cliquer sur le chevron gauche comme pour aller à la page 1 pour voir les résultats
@Bonvallot peux-tu vérifier si ça marche comme ça de ton côté ?
@touv le filtrage front ou admin utilise le même module lodex ?

**Comment by yannguillemin** [comment]
Je précise le problème d'une façon plus générale : 
le champ de recherche d'une facette est opérant sur l'ensemble des éléments s'il est utilisé à partir de la première liste de mots, en revanche si la recherche s'effectue à partir d'une autre page N de liste d'éléments, seuls les éléments à partir de la page N+1 sont détectés.
Par ailleurs, il serait intéressant que le bouton "clear all" de réinitialisation efface ce qui a été entré dans le champ de recherche, car même si la réinitialisation est effective, celle-ci ne se fait pas sur la liste des éléments affichés (seul l'élément précédemment recherché reste apparent).
Problème constaté sur la v14.0.60

**Comment by Bonvallot** [comment]
Quand en front, je suis sur la deuxième page d'une facette et que je saisis un terme présent dans la première page, j'obtiens le résultat désiré
ok pour moi

Par contre, quand on supprime tous les filtres, la valeur recherchée est toujours et seule présente.

**Comment by vresz** [comment]
ok pour moi
Mais même problème avec le bouton "Tout supprimer" la recherche reste présente, quelque soit la page de la facette

**Comment by jonathanarnault** [comment]
Correction effectuée

**Comment by Alexmarmelab** [comment]
A la suppression d'une seule facette, vider le champ de recherche de la facette en question.

Conserver le contenu du champ de recherche principal

**Comment by jonathanarnault** [comment]
Correction effectuée

**Comment by AnaelKremer** [comment]
Ok pour moi

**Comment by vresz** [comment]
Ok pour moi

**Comment by eonm-pro** [comment]
Testé en 14.0.75

Ok pour moi
