### ISSUE TITLE
(0,5) Recherche en back insensible aux diacritiques

### ISSUE THREAD

**Issue by camilledesalabert** [Inist-CNRS/lodex#2131]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire**.
Quand on filtre en back sur des colonnes qui contiennent des chaînes de caractères comportant des diacritiques, on ne peut pas utiliser une forme appauvrie.

**Décrivez la solution que vous souhaitez**
En front, la recherche n'est pas sensible aux diacritiques. Ce serait une avancée qu'elle le soit aussi en back !

**Contexte supplémentaire**
Dans le corpus "Prix Nobel et Médailles Fields" par exemple, il n'est pas aisé de rechercher des noms étrangers avec des caractères peu usuels au clavier. 
Exemples : 
![image](https://github.com/user-attachments/assets/741e931b-1b89-4cc2-b25b-6019919ec4d3)
![image](https://github.com/user-attachments/assets/fc75eaec-facf-4772-81d0-2f818ec7b220)

**Solution** 
En back > Données > Filtres, rendre insensible aux diacritiques l'input "Valeur" des filtres

**Comment by camilledesalabert** [comment]
En complément de cette demande, une recherche en back insensible à la casse, comme en front, serait un plus.

**Comment by eonm-pro** [comment]
@arnault-dev 

Dans l'ensemble la recherche insensible aux diacritiques et à la casse fonctionne, mais toutes les diacritiques ne peuvent pas être recherchées. Par exemple, il est impossible de trouver un texte contenant des [brèves](https://fr.wikipedia.org/wiki/Br%C3%A8ve) comme : `ğ` ou des [macrons](https://fr.wikipedia.org/wiki/Macron_(diacritique)) comme : `ā` (même lorsque l'on recherche précisément le caractère).

Si l'une de mes cellules contient `eğim` même en recherchant `eğim` ou `egim` je ne trouve aucun résultat.

**Comment by Bonvallot** [comment]
j'ai pu retrouver "undefined Ngô Báo Châu" en recherchant ngo ou bao ou chau

**Comment by Alexmarmelab** [comment]
Repasser sur les caractères un peu moins courants + les ligatures « æ » (ou « Æ ») et « œ » (ou « Œ »)

**Comment by eonm-pro** [comment]
Il existe une liste de substitution dans la librairie latinize.

https://github.com/dundalek/latinize/blob/master/latinize.js#L12-L914

**Comment by touv** [comment]
[deburr](https://lodash.com/docs/4.17.15#deburr)
utilise cette table https://en.wikipedia.org/wiki/Combining_Diacritical_Marks

**Comment by jonathanarnault** [comment]
Correction effectuée

**Comment by Alexmarmelab** [comment]
**Vu au daily** : cette carte peut être passée en done si elle est validée par **deux** personnes

**Comment by eonm-pro** [comment]
Testé en 14.0.74:

OK pour moi.

**Comment by vresz** [comment]
J'ai pu trouver "archäologisches" en cherchant archao

**Comment by Bonvallot** [comment]
ok pour v.14076 avec ernahrung qui retrouve Ernährung
