### ISSUE TITLE
Customisation police/taille du "headTitle" et des titres de ressources/graphiques pour le thème "voscouleurs"

### ISSUE THREAD

**Issue by yannguillemin** [Inist-CNRS/lodex#2154]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire**.
Un utilisateur externe souhaiterait pouvoir changer la police et la taille des caractères pour le titre de la bannière ("headTitle") ainsi que pour les titres ("étiquettes") des ressources et graphiques. 

**Décrivez la solution que vous souhaitez**
La "customisation" est déjà possible pour les couleurs du "headtitle" ainsi que pour les titres des graphiques via le script de configuration du thème. Serait-il envisageable de pouvoir le faire aussi pour les titres des ressources et étendre la configuration de ces 3 items aux choix de la police et de la taille des caractères ?

**Décrivez les alternatives que vous avez envisagées**
Externaliser les variables CSS concernées dans le script de configuration du thème.

**Comment by touv** [comment]
@HeleneCreusot est-ce possible ?
