### ISSUE TITLE
Export des données au format ".ris" KO

### ISSUE THREAD

**Issue by yannguillemin** [Inist-CNRS/lodex#2156]
**Décrire le bogue**
L'export des données à partir de l'onglet "Search" n'est plus fonctionnel.

**Reproduire**
Étapes pour reproduire le comportement :

1. Allez sur n'importe quelle instance.
2. Cliquez sur l'onglet "Search" puis sur le bouton "EXPORT" et sélectionner le format "RIS - Research Information Systems"
3. Ouvrir le fichier téléchargé.
4. On obtient le résultat suivant répété sur x lignes : 

TY  - GENERIC
ER  -

TY  - GENERIC
ER  -

TY  - GENERIC
ER  -

TY  - GENERIC
ER  -

**Comportement attendu**
Rendre l'export au format RIS fonctionnel.

- Version de LODEX [14.0.61]

**Contexte supplémentaire**
En attendant, peut-être désactiver ce format d'export dans le fichier de configuration des instances par défaut ?

**Comment by touv** [comment]
L'export RIS fonctionne uniquement si les champs ont été "sémantisés" cad  qu'une url sémantique a été ajoutée dans la configuration du champ. En l'absence de ce paramétrage, l'export RIS ne fonctionnera pas.

Autre problème, la [documention]( https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/comment-sen-servir/)
n’indique pas l'existence de ce format d’export, elle ne précise pas non plus quelles propriétés sémantiques il faut choisir pour pourvoir réaliser un export RIS riche et conforme.  

Dans ces conditions, effectivement, il est inutile d’activer ce format d’export par défaut.

**Comment by touv** [comment]
@eonm-pro @camilledesalabert attention dans vos instances, lors de la prochaine mise à jour, l'export ris devra être réactivé manuellement
