### ISSUE TITLE
[14.0.62] Le format Lodex-field ne fonctionne plus

### ISSUE THREAD

**Issue by sbarreaux2** [Inist-CNRS/lodex#2170]
Le format Lodex-Field n'affiche plus les informations qu'il devrait afficher

**Reproduire**
Étapes pour reproduire le comportement :

1. Allez dans  l'instance "ClimatoRisques" (https://instance-globale-14062.lodex-dev.inist.fr/instance/climatorisques/)
2. Cliquez sur l'onglet Recherche puis sur une ressource
3. Chercher le champ "Editeur" ou le champ "Langue de publication"
4. Les 2 champs affichent "Une erreur est survenue en essayant de récupérer les données du graphique"

**Comportement attendu**
Le champ éditeur doit afficher les informations 

**Captures d'écran**
![image](https://github.com/user-attachments/assets/cbf72317-fc9f-4bc3-a7cf-9b9b3e4ffb22)
![image](https://github.com/user-attachments/assets/b551a32b-6844-41bb-842a-dd1c0f3095c2)

**Environnement (veuillez compléter les informations suivantes) :**

- Navigateur : firefox
- Version de LODEX : 14.0.62 (constaté aussi en 14.0.57)

**Contexte supplémentaire**
pour wiley, affiche les informations provenant de https://scientific-publisher.data.istex.fr/ark:/67375/H02-QW5Q88H5-V
pour anglais, affiche les informations provenant de https://publication-language.data.istex.fr/ark:/67375/

**Comment by yannguillemin** [comment]
Déjà, je vois un problème au niveau des transformations de remplacement pour l'éditeur afin d'accéder à l'adresse https://scientific-publisher.data.istex.fr/ . Je peux m'en occuper, mais cela ne règle pas le problème pour autant, je viens de tester avec Springer.
Je viens de faire un test entre deux de mes instances sur dev-lodex et il y a effectivement aussi un problème qui semble venir du formatage qui ne fait plus le lien entre deux ressources issues d'instances différentes.

**Comment by sbarreaux2** [comment]
Le problème ne vient pas des transformations puisque les informations s'affichent très bien dans l'instance en prod sur data.istex avec une version 12.55.2 de lodex (https://traduction-machinetranslationv2.corpus.istex.fr/uid:/22NTMVcLm).
Le problème vient de la version 14 qui ne permet pas de faire le lien entre 2 instances (une en V14 et une en V12)

**Comment by yannguillemin** [comment]
La colonne "Éditeur_Istex" était initialement vide en prévisualisation pour Springer et j'avais modifié la transformation ("Springer International pubishing" au lieu de "springer-journals" à partir de la colonne "Éditeur".
Cela vient de faire effet, mais j'ai du mal à comprendre ce qui cause le problème de lien pour le reste.
Je continue de chercher.
<img width="394" alt="image" src="https://github.com/user-attachments/assets/6a606a65-729a-4c7a-af3c-e2a2d9ef8049">

**Comment by sbarreaux2** [comment]
Le paramétrage du champ Editeur "dh1u" est bon, **il ne faut pas le modifier**. Par les transformations réalisées, on souhaite remplacer la valeur contenue dans la colonne par un lien vers la page de l'instance [https://scientific-publisher.data.istex.fr](https://scientific-publisher.data.istex.fr/ark:/67375/H02-QW5Q88H5-V) décrivant l'éditeur et le format lodex champ permet de récupérer la valeur des champs "Nom Editeur - forme retenue" et "Site internet" pour les afficher dans l'instance machine-translationv2. C'est la récupération de ces valeurs qui ne fonctionne pas

**Comment by yannguillemin** [comment]
Ok, c'est noté, je viens d'annuler mes modifications.
Ceci étant, les chaînes de caractères à remplacer dans les transformations "REPLACE" de la ressource [dh1u] ne correspondent pas à celles présentes dans la colonne "Éditeur_Istex".

**Comment by sbarreaux2** [comment]
Effectivement, c'est particulier pour cette instance. Mais dans l'instance [ClimatoRisques](https://instance-globale-14062.lodex-dev.inist.fr/instance/climatorisques/), ça fonctionne comme décrit dans l'issue

**Comment by yannguillemin** [comment]
Oui, j'ai retrouvé le problème dans d'autres instances faisant appel à des ressources encore en V12.
Tout ce que je peux dire pour le moment, c'est que ce format fonctionne pour lier des ressources entre deux V14.

**Comment by yannguillemin** [comment]
Pour info, je vais clôturer cette issue et en créer une nouvelle pour préciser le fond du problème dans le titre.

**Comment by yannguillemin** [comment]
Issue recréée : #2173.
