### ISSUE TITLE
[14.0.62] espace sous graphique

### ISSUE THREAD

**Issue by sbarreaux2** [Inist-CNRS/lodex#2171]
Un grand espace est présent entre le graphique "répartition par année" et sa légende dans le corpus climatoRisques (https://instance-globale-14062.lodex-dev.inist.fr/instance/climatorisques).
Le comportement est similaire en page d'accueil et en page Graphiques.
Il s'agit d'un Graphique - Syntaxe Vega-Lite
![image](https://github.com/user-attachments/assets/f671c110-9c46-49bb-a6ca-c21feca2837d)

Idem dans le corpus Vieillissement (https://instance-globale-14062.lodex-dev.inist.fr/instance/vieillissement) pour les graphiques Analyse 10 thématiques Topic Modeling et Analyse 20 thématiques Topic Modeling.
Le comportement est similaire en page d'accueil et en page Graphiques v(même si c'est moins gênant en page graphique)
Il s'agit d'un Graphique - Diagramme en barres
![image](https://github.com/user-attachments/assets/8c11f55a-282e-4575-aa8a-88e502c1f0aa)

**Comment by yannguillemin** [comment]
Pour les graphiques édités avec vega-lite de la première instance, il n'y a pas de hauteur déclarée, on peut pallier à cela par exemple en spécifiant la hauteur pour qu'elle s'ajuste au conteneur en ajoutant "height":"container" (généralement en dessous ou au dessus de la spécification de la largeur). Je viens de le faire pour le bubble plot "Risques naturels et dates" et le diagramme à barres "répartition par années" du premier corpus.

**Comment by yannguillemin** [comment]
Pour la deuxième instance et les deux diagrammes Top 10 et Top 20 "Topic Modeling", j'ai fait à peu près la même en passant par l'éditeur Vega-Lite pour remplacer :
  "width": "container",
  "height": {
    "step": 20
  },
par :
  "width": "container",
  "height": "container",
