### ISSUE TITLE
[14063] Graphique Cartographie - Projection française : les départements ne s'affichent plus dans la tooltip

### ISSUE THREAD

**Issue by nantonot** [Inist-CNRS/lodex#2195]
En v14063, les départements sur le graphique carte de France ne s'affichent plus dans la tooltip :
![image](https://github.com/user-attachments/assets/9ba57ba2-f469-4789-b0fa-ce00c2da7f33)
Voir : http://192.168.31.238:49365/instance/test-energie-echantillon/graph/Ixzc

Alors que dans la v12554, ils s'affichaient :
![image](https://github.com/user-attachments/assets/f709af42-e4c8-4b1e-8420-bffb4b55994a)
Voir : http://192.168.31.238:49369/graph/YQOm

Serait-ce possible de rétablir cet affichage ?

**Comment by yannguillemin** [comment]
En attendant de modifier le formatage par défaut du "Graph - Cartography" pour adapter le code vega-lite automatiqument généré, il est possible de le faire à la main en supprimant les lignes suivantes (ne pas associer la propriété NAME_0 à un champ car elle correspond au nom du pays).
Ex en V14.0.63 : https://lodex-dev.inist.fr/instance/demo-climat/graph/LuFk
    "tooltip": [
        <s> {
        "field": "properties.NAME_0",
        "type": "nominal",
        "title": "Département" ou "autres"
      },</s>
      {
        "field": "properties.NAME_1",
        "type": "nominal",
        "title": "Région"
      },
      {
        "field": "properties.NAME_2",
        "type": "nominal",
        "title": "Département"
      },
      {
        "field": "value",
        "type": "quantitative",
        "title": "Nb Publis"
      }
    ]

**Comment by yannguillemin** [comment]
Après tentative de recréation d'une carte française avec la V14, il s'avère que cette partie de code à supprimer n'est pas générée automatiquement. Cela devait fonctionner avant dans une précédent version de l'API Vega-Lite où le dernier champ déclaré semblait prendre le dessus dans le cas de champs identique, ce qui n'est plus le cas actuellement.

**Comment by yannguillemin** [comment]
En complément, si l'info-bulle venait à être renseignée via l'interface graphique, il faut bien entrer "Département" pour le champ "Category" sinon, il y a interférence avec le code Vega-Lite et on peut obtenir la chose suivante : 
![image](https://github.com/user-attachments/assets/d9d1b2b1-43d5-4f09-8818-a3c86d818172)

**Comment by yannguillemin** [comment]
Corrigé par la PR #2267.
Remarque : ne rien renseigner dans le champ "Catégorie" pur l'info-bulle.
