### ISSUE TITLE
(0,25) Eviter la multiplication des appels lors de la saise d'un enrichissement

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2203]
**Décrire le bogue**
Lors de saisie avancée d'un enrichissement, à chaque touche appuyée génère une requête HTTP et un traitement

**Reproduire**

Saisir plusieurs lignes vides

**Captures d'écran**

[Screencast_00012.webm](https://github.com/user-attachments/assets/ea291d74-3cf1-4310-8dcf-8a17d1283e36)

**Comment by touv** [comment]
problème qui semble similaire à celui-ci https://plainenglish.io/community/how-to-cancel-fetch-and-axios-requests-in-react-useeffect-hook

**Comment by Alexmarmelab** [comment]
Solution : mettre en place un debounce

**Comment by eonm-pro** [comment]
@arnault-dev 

Testé sur un enrichissement avancé. Le debounce fonctionne bien

**Comment by AnaelKremer** [comment]
Ok aussi
