### ISSUE TITLE
Impossibilité de publier une instance Lodex lorsque les données jsonl contiennent `lodex_published`

### ISSUE THREAD

**Issue by eonm-pro** [Inist-CNRS/lodex#2207]
Lorsqu'on importe un jeu de données jsonl contenant un clé `lodex_published`, il n'est pas possible de le publier sur lodex. Le bouton "publier" du back end n'a aucun effet.

```json
{"uri":"ark:/67375/P5F-21PDK04C-7","Nom du corpus":"Mémoire-Neurosciences","Lien vers instance Lodex":"https://memoire-neurosciences.corpus.istex.fr/","lodex_published":true}
{"uri":"ark:/67375/P5F-8H1D4JN0-B ","Nom du corpus":"Mémoire-Neurosciences-V2","Lien vers instance Lodex":"https://memoire-neurosciencesv2.corpus.istex.fr/","lodex_published":true}
```

Ce bug a été observé lors de la migration d'anciennes instances Lodex (inistcnrs/lodex-theme-istex:12.23.33) vers de nouvelles instances (inistcnrs/lodex-theme-istex:12.55.4). Le bug affecte également la version 14.0.63 de Lodex.

**Reproduire**

Depuis le backend d'une instance Lodex :

1. Importer le jeux de données jsonl avec l'importer `JSON - import Lodex`.
2. Ajouter des éléments à l'affichage/ou importer un modèle.
3. Cliquer sur publier.
4. Les données ne sont pas publiées sur l'instance, l'icône de l’œil qui permet de se rendre sur l'affichage public de l'instance n'apparait pas non plus.

![image](https://github.com/user-attachments/assets/0d33b46b-d77d-41ff-931e-46f78a420b3a)

**Environnement :**
- Google Chrome Version 130.0.6723.70 (Build officiel) (64 bits)
- également testé sur Firefox Nightly (134.0a1)
- cnrsinist/lodex:14.0.63

**Comment by touv** [comment]
une solution possible serait d'ajouter une règle dans les loaders qui supprime cette colonne

**Comment by yannguillemin** [comment]
Le problème venant du caractère "_" qui semble réserver à JavaScript, une solution pourrait consister à traiter ce caractère comme ce qui est fait pour les points. Lodex gère déjà cela en supprimant les points des intitulés de colonnes, il faudrait juste ajouter l'underscore dans la liste des caractères à supprimer. D'ailleurs, il faudrait aussi ajouter le tiret "-", j'avais eu un problème avec ça , mais à l'époque l'import des données ne se faisait même pas.

**Comment by yannguillemin** [comment]
Si je prends l'exemple du loader jsonl, c'est clairement explicite pour le point.
```
# Prevent keys form containing dot path notation (which is forbidden by nodejs mongoDB driver)
[OBJFlatten]
separator = fix('.')
reverse = true
```

**Comment by yannguillemin** [comment]
Dans le cas présent le problème semble venir du caractère "underscore" (cad que tout fonctionne si on l'enlève), mais je viens de faire un test avec des données dont les colonnes sont nommées "dataset_A_1"..., et là tout fonctionne en l'état. Donc je retire ce que j'ai pu dire précédemment.

**Comment by touv** [comment]
lodex_published est un mot clé réservé utilisé en interne https://github.com/search?q=repo%3AInist-CNRS%2Flodex%20lodex_published&type=code

**Comment by yannguillemin** [comment]
2 solutions possibles :
1. renommer la colonne en question avant import
2. charger les données de la colonne en question dans un champ avec un autre nom et supprimer la colonne en fiasnat tout cela dans le loader comme dans l'exemple ci-dessous

![image](https://github.com/user-attachments/assets/a911c984-8e6a-4d69-8f3e-fd07c92946cc)
