### ISSUE TITLE
Graphe VegaLite courbe évolution annuelle incomplet à l’affichage

### ISSUE THREAD

**Issue by egentilini** [Inist-CNRS/lodex#2215]
Nous avons dans une instance Lodex, un graphe en vegalite pour représenter des courbes d’évolution annuelle de 3 variables.
Pour une année, une valeur est affichée à zéro alors qu’il existe bien des données (visibles dans l’éditeur de code Vegalite de l’interface admin). Capture ci-dessous.
Selon le filtre appliqué sur les données, la valeur affichée à zéro change (d’année et de variable).

Version de LODEX 14.0.62
Navigateurs utilisés : Chrome et Firefox

![Picture](https://github.com/user-attachments/assets/97166bc1-d1d4-4e38-8fb4-5a5ea2754310)

**Comment by AnaelKremer** [comment]
Bonjour, difficile à dire sans plus d'informations.
Quelles données sont utilisées pour ce graphique (des nombres, des strings ?). Ont-elles bien toutes le même format ?
Quelle est la routine utilisée ?

L'idéal serait évidement d'avoir accès aux données :)

**Comment by egentilini** [comment]
Bonjour,

Nous avons trouvé la solution grâce à Nicolas Thouvenin. Il s'agissait du paramétrage du nombre max de champs.

Pour l'accès aux données, malheureusement notre direction ne nous autorise pas à les diffuser. Ce qui rend plus compliqué les explications pour décrire les bugs.

Merci cependant pour votre aide. :)
