### ISSUE TITLE
Disparition du message d'alerte lors de l'import d'un model

### ISSUE THREAD

**Issue by AnaelKremer** [Inist-CNRS/lodex#2242]
Lorsque l'on importe un model dans la 14.0.66 on n'a plus le message d'alerte qui disait que le model contient des enrichissements et qu'ils est nécessaire de les relancer. On a d'ailleurs l'impression qu'il ne se passe rien du tout, le model est bien chargé mais il nécessaire de rafraîchir plusieurs fois le page pour le constater.

**Comment by yannguillemin** [comment]
Je viens d'essayer de reproduire le bug et j'ai bien le message qui indique que le modèle contient des enrichissements. C'était peut-être un dysfonctionnement transitoire ? Ou il est spécifique à ton instance ? Est-ce que t'arrives à le reproduire ? Si non, je clôture l'issue, mais en attendant je mets le label "parking".
![image](https://github.com/user-attachments/assets/f06c355f-172e-4ceb-a9ef-acc545fe1d6a)

**Comment by yannguillemin** [comment]
@AnaelKremer, vu que ça refonctionne pour l'instance où tu avais eu le problème, je clôture l'issue comme convenu.

**Comment by parmentf** [comment]
J'ai eu pas mal de problèmes réseau (même en interne) ce jour-là, ça peut en être la cause.
