### ISSUE TITLE
chargement d'un fichier CSV impossible 

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2243]
**Décrire le bogue**
impossible de charger un fichier CSV, d'autres chargements fonctionnent

**Reproduire**
Étapes pour reproduire le comportement :

inconnu

**Captures d'écran**
Logs au moment du problème 

![2024-12-03_11-06](https://github.com/user-attachments/assets/f08fcfd6-a581-4431-94dd-801910a83bb2)

**Comment by yannguillemin** [comment]
@touv : tu aurais le CSV en question ? apparemment, la première ligne serait vide ?

**Comment by touv** [comment]
> @touv : tu aurais le CSV en question ? apparemment, la première ligne serait vide ?

je n'ai pas de fichier, j'ai juste noté ce que l'on me rapporte, peut-être faut-il tester avec un fichier sans entete ou avec une ligne blanche pour voir si on a le même pb

**Comment by yannguillemin** [comment]
Je viens de tester et ça ne gêne pas le chargement des données. LODEX nomme lui-même les colonnes (0, Column#1, Column#1, Column#2...) et mets la colonne "0" en premier devant l'uri. Les données sont chargées, mais le traitement sera compliqué...Dans la plupart des logiciels dédiés "data", les lignes vides sont à proscrire dans les csv.
Comme je n'arrive à reproduire le problème, j'ajoute le tag "parking" à la place de "Major Defect".
 
![image](https://github.com/user-attachments/assets/6f51946e-8ee1-4450-b7b0-e3cc8e1c0627)

**Comment by yannguillemin** [comment]
Même avec deux lignes vides, le chargement se fait quand même.
![image](https://github.com/user-attachments/assets/75530516-052e-4ca8-9212-013b1cb8268e)

**Comment by yannguillemin** [comment]
Je viens de remarquer dans le premier message que le navigateur utilisé était Firefox. Comme l'import de csv sans première ligne fonctionne actuellement très bien avec Firefox et les autres navigateurs (Chrome ou Brave entre autres), et au vu de certains problèmes qui sont assez souvent uniquement à Firefox, on peut soupçonner une une installation corrompue.
Pour tenter d'y remédier, il peut être intéressant de réparer l'installation (option accessible en tentant une désinstallation du navigateur).
![image](https://github.com/user-attachments/assets/011f8a74-1a23-4da0-9686-87b881d19ab3)
