### ISSUE TITLE
visuel des blocs dans thème Istex générique [format Liste + Lodex - Ressource]

### ISSUE THREAD

**Issue by sbarreaux2** [Inist-CNRS/lodex#2246]
Dans la version 14.0.66, le **thème Istex générique** affiche les blocs avec du texte surligné pour indiquer que le texte est cliquable.

![image](https://github.com/user-attachments/assets/08ae33bb-675e-40bf-922e-5aceb3d9e494)

Ce surlignage alourdit l'affichage des blocs et nuit à l'ergonomie globale de la page. Il indique que seul le texte est cliquable, mais c'est le bloc complet qui doit être cliquable.

**Décrivez la solution que vous souhaitez**
- Il faudrait enlever le surlignage et ajouter une petite flèche bleue en bas à droite du bloc.
- Le bloc complet doit être cliquable pour accéder à l'instance vers laquelle il renvoie (pas seulement le texte)
- Le bloc doit être moins large. On doit pouvoir afficher 3 blocs sur 1 ligne lorsqu'il n'y a pas de sidebar bleue (cf. https://loaded-corpus.data.istex.fr/ quand le thème sera appliqué) et 2 blocs sur 1 ligne lorsqu'il y a une sidebar
- Le bloc doit être un peu plus haut. On doit pouvoir afficher un texte explicatif de quelques lignes le cas échéant (cf https://scientific-publisher.data.istex.fr/) 

**Contexte supplémentaire**
Le format utilisé pour afficher ces blocs est : **Texte - liste de valeurs** (liste désordonnée sans puce) + **Lodex - Ressource**.
En valeur arbitraire, on met une liste d'ARKs

**Comment by touv** [comment]
@HeleneCreusot je te laisse le soin de regarder le pb

**Comment by HeleneCreusot** [comment]
@sbarreaux2  Bonjour, le theme istex générique nécessite l'usage des class internes. Sont-elles utilisées dans cette instance ?

dans le cas cité : class interne ContentListePave

[documentation class internes ](https://github.com/Inist-CNRS/lodex/tree/master/src/app/custom/themes/istex#readme)

**Comment by sbarreaux2** [comment]
@HeleneCreusot Hello, non je n'avais pas utilisé de classe interne. J'avais repris le modèle de data.istex en prod qui est dans une version antérieure (14.0.57). 
C'est beaucoup mieux avec la classe interne ContentListePave ! Merci
Mais les blocs restent affichés sur 1 colonne. Est-ce possible de les afficher sur 2 colonne voir 3 (quand il n'y a pas la sidebar bleue) ?

**Comment by HeleneCreusot** [comment]
@sbarreaux2 est-ce que tu as mis un pourcentage de largeur dans l'affichage du bloc ?

**Comment by sbarreaux2** [comment]
@HeleneCreusot je n'ai pas touché au pourcentage de largeur, c'était resté par défaut à 100%. Mais là je constate que les blocs se mettent sur 2 colonnes avec sidebar et sur 3 quand il n'y a pas de sidebar. Je pense donc qu'il n'y a plus d'issue. Mais je ne comprends pas ce qui a changé depuis mon essai où ça s'affichait sur 1 colonne
