### ISSUE TITLE
visuel des blocs dans thème Istex générique [format grille de ressource]

### ISSUE THREAD

**Issue by sbarreaux2** [Inist-CNRS/lodex#2247]
Dans la version 14.0.66, le thème Istex générique affiche les blocs gris sur un fond gris.

![image](https://github.com/user-attachments/assets/8bffd50e-1af0-40b3-932b-845c5e302c9d)

Rien ne délimite le périmètre des blocs et n'indique qu'il faut cliquer quelque part

### Décrivez la solution que vous souhaitez
- Il faudrait que le bloc soit blanc avec une ombre
- Il faudrait ajouter une petite flèche bleue en bas à droite du bloc
- Il faut conserver le fait que le bloc complet soit cliquable pour accéder à l'instance vers laquelle il renvoie 
- Il faut conserver la largeur et la longueur du bloc ainsi que la possibilité d'afficher 3 blocs sur 1 ligne lorsqu'il n'y a pas de sidebar bleue (cf. https://named-entity.data.istex.fr/ quand passera sur ce thème) et seulement 2 blocs sur 1 ligne lorsqu'il y a une sidebar

### Contexte supplémentaire
Le format utilisé pour afficher ces blocs est : **Autre - Grille de ressource**.
En valeur arbitraire, on met la routine /api/run/syndication

**Comment by touv** [comment]
@HeleneCreusot est-ce possible de faire quelque chose ?

**Comment by HeleneCreusot** [comment]
je mets à jour la doc en conséquence car il n'est pas fait mention de "ContentListePave"

@sbarreaux2  Bonjour, le theme istex générique nécessite l'usage des class internes. Sont-elles utilisées dans cette instance ?

dans le cas cité : class interne ContentListePave

[documentation class internes ](https://github.com/Inist-CNRS/lodex/tree/master/src/app/custom/themes/istex#readme)

**Comment by sbarreaux2** [comment]
@HeleneCreusot Hello, non je n'avais pas utilisé de classe interne. J'avais repris le modèle de data.istex en prod qui est dans une version antérieure (14.0.57).
C'est beaucoup mieux avec la classe interne ContentListePave ! Merci
Mais les blocs restent affichés sur 1 colonne. Est-ce possible de les afficher sur 2 colonne voir 3 (quand il n'y a pas la sidebar bleue) ?
