### ISSUE TITLE
Voyant mémoire vive (RAM usage) saturée sur la VM Lodex IN2P3

### ISSUE THREAD

**Issue by LucileBgg** [Inist-CNRS/lodex#2248]
**Description et reproduction du bogue**
- La machine de production Lodex IN2P3 possède plusieurs instances en v12. Au passage en v14 (et après la création de 2 containers-maîtres possédant chacun 1 instance remplie, il n'était plus possible de créer de nouvelles instances et le voyant RAM usage indiquait une saturation (98%). 2 nouveaux containers-maîtres de type "instance globale" et redirection ont été créés, cependant il ne semblait possible d'y accéder.
- Il est à noter qu'il ne s'agit d'un manque de stockage de données (13% en Data HD usage et 47% en docker HDD usage)
- Après un nettoyage et suppression des containers-maîtres créés (sauf 1 pour le moment à conserver), le voyant RAM usage est repassé à 80%. Cependant il est à supposer qu'à la création de plusieurs nouvelles instances dans une instance-maître en v14, nous rencontrions de nouveau le même scénario.

**Comportement attendu**
Diminuer le RAM usage afin de permettre la création et la gestion de nouvelles instances en v14

**Environnement (veuillez compléter les informations suivantes) :**

- Testé sous Chrome et Firefox
- LODEX 14.0.61

![saturation-ram-usage](https://github.com/user-attachments/assets/4d087a50-147b-43be-bf7b-f57a3dc0000a)

**Comment by touv** [comment]
La demande a été faite pour le réglage adéquat de la machine

**Comment by touv** [comment]
J'en profite pour indiquer que le dimensionnement d’une architecture technique dédiée à Lodex dépend fortement du volume de données, de l’intensité du trafic généré et du choix de certains graphiques/routines. Certains calculs sont plus gourmands que d’autres.

Lodex fonctionne sur des serveurs Linux plutôt modestes, avec à minima 4 CPUs correspondant au 4 middlewares sous-jacents (serveur web, base de données, serveur de traitements, serveur de tâches de fond)  avec 32 Go de RAM et 64 Go de disque dur.

En cas de problème, on peut doubler cette configuration.

@yannguillemin peut-être devrions-nous l'indiquer quelque part dans la documentation ?

**Comment by yannguillemin** [comment]
@touv : ok, je vais rajouter ce point dans la FAQ.

**Comment by yannguillemin** [comment]
@touv : J'ai bien ajouté tes précisions dans la FAQ, et vu que la demande a été faite pour augmenter les ressources de la machine de l'IN2P3, je me permets de clôturer l'issue.
