### ISSUE TITLE
Contrôle des données à l'export

### ISSUE THREAD

**Issue by LaurelineLemoine** [Inist-CNRS/lodex#2261]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire**.
Quand un utilsateur exporte les données, l'export comporte des données intermédiaires qui servent à des traitements et qui n'ont pas vocation à être visibles.

**Décrivez la solution que vous souhaitez**
En tant qu'administrateur de mon lodex je voudrais pouvoir décider des colonnes à afficher/masquer dans les exports possibles pour l'utilisateur.

**Décrivez les alternatives que vous avez envisagées**

**Contexte supplémentaire**
Exemple pour les exports du lodex BibCNRS Index : pour ne pas surcharger les chercheurs et documentalistes avec des données inutiles et améliorer l'ergonomie de l'outil Lodex pour une meilleure expérience utilisateur.

**Comment by touv** [comment]
On pourrait imaginer répondre à ce besoin par une nouvelle interface de configuration des exports, ce qui nécessite des développements informatiques spécifiques, donc du temps (et donc de l’argent)

Mais dans Lodex, il est possible de créer autant de formats d'export que l'on souhaite, il suffit d'une part de créer la configuration souhaitée et d'autre part de les activer dans le fichier global de configuration.
Évidemment, cette modification n’est pas dynamique, il faut arrêter lodex et redémarrer. Par exemple, il existe un format [csv-full](https://github.com/Inist-CNRS/lodex/blob/master/workers/exporters/csv-full.ini) qui ajoute à chaque ressource les métadonnées du dataset.

Il est donc possible de créer des exports spécifiques au cas d’usage mentionné ici. Mais à mon sens ce besoin révèle plutôt une incohérence dans le comportement des exports. Actuellement, si un champ est marqué comme caché (pour des traitements intermédiaires, par exemple), il reste exportable…


Du coup, je propose plutôt de modifier les exports par défaut (CSV et JSON) pour qu’ils exportent seulement les informations affichées. En cas de besoin contraire, on pourra toujours faire des exports spécifiques.

**Comment by LaurelineLemoine** [comment]
Bonjour,

Merci pour cette réponse, nous testerons la configuration des exports par défaut avec Mélanie Marcon sur le lodex des ressources BbibCNRS,

Cordialement,


Laureline LEMOINE
Chargée de l’animation et de la coordination BibCNRS – Click & Read
Service Portails & Plateformes
***@***.******@***.***>

Institut de l’information scientifique et technique
CNRS | DGDS | DDOR
2, rue Jean-Zay - 54519 - Vandoeuvre-lès-Nancy - France
https://www.inist.fr/
https://x.com/BibCnrs
https://x.com/_ClickandRead

De : Nicolas Thouvenin ***@***.***>
Envoyé : mercredi 11 décembre 2024 12:29
À : Inist-CNRS/lodex ***@***.***>
Cc : LEMOINE, Laureline ***@***.***>; Author ***@***.***>
Objet : Re: [Inist-CNRS/lodex] Contrôle des données à l'export (Issue #2261)


On pourrait imaginer répondre à ce besoin par une nouvelle interface de configuration des exports, ce qui nécessite des développements informatiques spécifiques, donc du temps (et donc de l’argent)

Mais dans Lodex, il est possible de créer autant de formats d'export que l'on souhaite, il suffit d'une part de créer la configuration souhaitée et d'autre part de les activer dans le fichier global de configuration.
Évidemment, cette modification n’est pas dynamique, il faut arrêter lodex et redémarrer. Par exemple, il existe un format csv-full<https://github.com/Inist-CNRS/lodex/blob/master/workers/exporters/csv-full.ini> qui ajoute à chaque ressource les métadonnées du dataset.

Il est donc possible de créer des exports spécifiques au cas d’usage mentionné ici. Mais à mon sens ce besoin révèle plutôt une incohérence dans le comportement des exports. Actuellement, si un champ est marqué comme caché (pour des traitements intermédiaires, par exemple), il reste exportable…

Du coup, je propose plutôt de modifier les exports par défaut (CSV et JSON) pour qu’ils exportent seulement les informations affichées. En cas de besoin contraire, on pourra toujours faire des exports spécifiques.
