### ISSUE TITLE
(0,5) Pouvoir accéder aux icônes "Dupliquer" et "Paramétrer" même quand le champ est peu large

### ISSUE THREAD

**Issue by jonathanarnault** [Inist-CNRS/lodex#2285]
**Problème**
J'édite un champ > Affichage > largeur : 20% et j'enregistre
-> je ne peux plus accéder aux icônes "Dupliquer" et "Paramétrer" qui paraissent au survol du champ

![Image](https://github.com/user-attachments/assets/aa8e067a-c5b6-4ee2-8702-9d100df2b931)

**Solution**
- Agrandir la hauteur des blocs "Champ" de façon à faire apparaître les icônes "Dupliquer", "Copier l'id" et "drag & drop" sous le nom interne au survol du champ
- Mettre les icônes "Dupliquer", "Paramétrer" et "Drag&drop" en couleur de façon à différencier les icônes informatives des icônes cliquables
- Si le contenu dépasse du bloc de la longueur du bloc, tronquer le texte
- Placer l'id (valeur violette entre crochets) avant le nom du champ pour qu'il ne soit pas tronqué

Ne pas inverser l'id et le titre sur toutes les interfaces (ex : onglet "Recherche et facettes")

<img width="919" alt="Image" src="https://github.com/user-attachments/assets/9b8c5939-285c-45d4-a36e-15c706dbd0dd" />

**Comment by Alexmarmelab** [comment]
**Vu au daily** : Pour les champs non visibles : retirer l'oeil, diminuer l'opacité et mettre le bord des champs avec des tirets

**Comment by eonm-pro** [comment]
Testé avec un bloc de 10% de largeur : les icônes sont bien visibles au survol et sont fonctionnelles.

**Comment by AnaelKremer** [comment]
testé avec des blocs à 5%, on ne peut pas cliquer sur la roue crantée, mais comme on l'avait dit ce bouton fait doublon avec le premier qui permet de drag & drop, car si on clique sur celui-ci on arrive aussi dans la configuration de la ressource.
![Image](https://github.com/user-attachments/assets/28e72ac6-8c4f-4417-8b32-4e36b1e67c33)
Mais effectivement, comme Mathis, ça marche avec 10% en largeur.

**Comment by Bonvallot** [comment]
Ok pour moi
Pour rappel, la largeur minimale avec la souris est de 10% 
Pour une largeur moindre, on est obligé de passer par l'affichage et saisir la valeur.

**Comment by vresz** [comment]
ok pour moi, jusqu'à 7%

**Comment by AnaelKremer** [comment]
On dit que c'est bon des champs a moins de 7% n'ont pas trop d'intérêt
