### ISSUE TITLE
After a while running, no connection possible

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#336]
When lodex has been running for a while (say, a day), you can't login except if you stop and start lodex again.

After typing your login and password, and clicking on `SIGN IN`, the user is redirected to the same page.

**Comment by parmentf** [comment]
Weird: just after a successful login on front, exporting the model (from the `ONTOLOGY` tab) redirects to http://inist-category.lod.istex.fr/login (v7.12.0, same instance)

**Comment by parmentf** [comment]
When you change `expiresIn` in [development-dist.js](https://github.com/Inist-CNRS/lodex/blob/master/config/development-dist.js#L7), from `10 * 3600` (ten hour) to `60` (one minute), you can reproduce the bug after very fewer time than a day.

**Comment by QuanticPotatoes** [comment]
This issue was fixed.
