### ISSUE TITLE
ISTEX query not correctly loaded/exported (?)

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#338]
Some ISTEX query is not like in the original file: `")` is appended to the initial query!
[langue-pub_ISTEX_QUERY.xlsx](https://github.com/Inist-CNRS/lodex/files/1003730/langue-pub_ISTEX_QUERY.xlsx)

Ex: `language:eng AND publicationDate:[1301 TO 1400]` became 
```
ISTEX search results for language:ger AND publicationDate:[1301 TO 1400]"):
Error
```

That is: `")` is appended to the query!

Query launched: https://api.istex.fr/document/?q=language%3Ager%20AND%20publicationDate%3A%5B1301%20TO%201400%5D%22)&from=0&size=10&output=id,title,publicationDate,fulltext,abstract

```
{
  "_error": "Erreur dans la composition du résultat. Contactez le support ISTEX."
}
```

```
HTTP/1.1 500 Internal Server Error
Date: Tue, 16 May 2017 08:56:11 GMT
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-XSS-Protection: 1; mode=block
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, OPTIONS
Content-Type: application/json; charset=utf-8
Content-Length: 86
Connection: close

```

See http://192.168.31.146:49244/uid:/WG7FZZ95

**Comment by parmentf** [comment]
This is not in nquadsextended exporter, but in the resource page, with the istex format!

![image](https://user-images.githubusercontent.com/595509/26888596-c28d52e6-4bab-11e7-8b35-34e85292d5ae.png)

**Comment by parmentf** [comment]
Ask Alain if it's still a bug, or if the problem raised from the data file.

In fact, the bug does not appear in http://192.168.31.146:49266/uid:/http%3A%2F%2Flexvo.org%2Fid%2Fiso639-3%2Feng

**Comment by yannguillemin** [comment]
Sorry François (@parmentf), but I have to close this issue because too old. Hoping that this was resolved at the time.
