### ISSUE TITLE
Refactor code to organize "routes" as entry point

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#363]
add new feature in Lodex is easy when we have a entrypoint like :
- formats
- transformers
- exporters
- loaders 
- reducers

A route is a special view of the dataset : 
 -  table view
 - over view
 - analytics view
 - etc.

It would be coherent and practical to organize routes as all other entry points

**Comment by parmentf** [comment]
Maybe do this during lodex/ezvis convergence.
