### ISSUE TITLE
Unable to edit fields with multi values

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#368]
![image](https://user-images.githubusercontent.com/15609/27033941-c906e2d0-4f7b-11e7-950c-ab4124fa52d7.png)

When click to save we get a dead lock

**Comment by touv** [comment]
see the latest version of  http://all-projects.dpi.inist.fr/ark:/67375/2BK-4RSPNT60-D

**Comment by parmentf** [comment]
See our slack on #triplex to get the data and the model, to reproduce.

Don't stay too long on this issue.

**Comment by touv** [comment]
fix in v8
