### ISSUE TITLE
Add a "Danger Zone" at the backoffice 

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#370]
that enable administrator to : 
- Clear the published data, keep uploaded dataset and model cf. https://github.com/Inist-CNRS/lodex/blob/master/makefile#L110
- Clear the whole database cf. https://github.com/Inist-CNRS/lodex/blob/master/makefile#L102

**Comment by touv** [comment]
![image](https://user-images.githubusercontent.com/15609/27628771-5caf80fc-5bf0-11e7-8d0b-2f92b358a9a9.png)

**Comment by QuanticPotatoes** [comment]
![image](https://user-images.githubusercontent.com/7420853/28270307-47114f04-6b05-11e7-8957-b82932fa6e2e.png)

![image](https://user-images.githubusercontent.com/7420853/28270296-362bc8ea-6b05-11e7-823d-b420e8a933ab.png)

Danger zone in **pull requests #402**

**Comment by parmentf** [comment]
#402 fixes that issue.
