### ISSUE TITLE
Show lodex version at the bottom of the front pages 

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#373]
with a small font, print : powered by lodex 15.4

**Comment by touv** [comment]
see package.json

**Comment by touv** [comment]
![image](https://user-images.githubusercontent.com/15609/27629058-554fec60-5bf1-11e7-83a3-246278c3640d.png)

**Comment by QuanticPotatoes** [comment]
![image](https://user-images.githubusercontent.com/7420853/28167914-9b2bef0c-67dd-11e7-85e5-845ff0cac282.png)
