### ISSUE TITLE
NQuads exports do not contain dataset properties

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#382]
Export should output dataset properties

**Comment by parmentf** [comment]
Bound to: the dataset should declare a Class too (skos:ConceptScheme, or ...)

Maybe add a setting `datasetClass` to give the Class of the dataset?

ex:
```
<https://example-dataset.data.istex.fr> a skos:ConceptScheme
```

See `skos:inScheme` and `dcterms:isPartOf`.

For `skos:inScheme`, the dataset's class is `skos:ConceptScheme`, but for `dcterms:isPartOf`, it's not defined, so one needs a means of declaring the class.

See [schemeForDatasetLink](https://github.com/Inist-CNRS/lodex/blob/90f5a34bd14388e4912d9b3c301ef4d2b3e18361/config.json#L36)

Maybe create a new issue for this comment?

**Comment by parmentf** [comment]
Le lien entre une ressource d’un jeu et le jeu (et ses métadonnées) est optionnel (voir `schemeForDatasetLink`). Dans le cas où il n’y a pas de lien, le triplet de lien n’est pas exporté. À traduire par un `linkDataset` `null` ou `false` dans `config.json` ?

**Comment by parmentf** [comment]
Export the dataset properties too (which `cover` is `dataset`).
