### ISSUE TITLE
format istex number of results: side effect on pagination

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#385]
![image](https://user-images.githubusercontent.com/595509/27434697-d80def5e-5759-11e7-9d8d-ca89748f7455.png)

See https://loaded-corpus.data.istex.fr/ark:/67375/XBH-4WZF4NWT-L

The number of results of the istex:query (379969) is also present in the number of pages (which should be 18)!

**Comment by touv** [comment]
see https://github.com/Inist-CNRS/lodex/blob/master/src/app/js/lib/fetchPaginatedDataForComponent.js#L75
see https://github.com/Inist-CNRS/lodex/blob/master/src/app/js/formats/istex/Component.js#L31

**Comment by parmentf** [comment]
Maybe `state.data.total` is shared between istex/Component and Pagination.

**Comment by parmentf** [comment]
Apologies: this is not a bug, but a pagination for the query's results.
