### ISSUE TITLE
Scheme autocompletion broken in the reverse-proxied version

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#391]
Autocompletion works within http://192.168.128.57:49214/home/ontology (when logged in)

![image](https://user-images.githubusercontent.com/595509/27482534-2be2f67e-5822-11e7-844d-e74de1a0b1c9.png)

but not within https://inist-category-5.data.istex.fr/home/ontology (same instance, accessed from outside or inside of the reverse-proxy).

**Comment by touv** [comment]
![image](https://user-images.githubusercontent.com/15609/27629877-014a86e0-5bf4-11e7-8ccb-1fd0a406671a.png)

**Comment by touv** [comment]
so use https:// instead http:// to call okfn

**Comment by QuanticPotatoes** [comment]
The protocol 'http' was replaced to 'https : 
https://github.com/Inist-CNRS/lodex/blob/b67b1d4d9891fb1be3b0def7dc7bd4c2d66af540/src/app/js/fields/FieldSchemeInput.js#L78
