### ISSUE TITLE
Each format should be applied to the values of an array

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#393]
we need to apply a format for each item of array value... and automatically build an html unordered list `<ul>`

**Comment by touv** [comment]
No, each format is different! Each format should be able to display a value array or a unique value.

For example:
- chart format can group each item in the same chart
- uri format can display a html list of uri
- paragraph format can separate each paragraph by a blank line
- etc.

**Comment by parmentf** [comment]
See what was done in #414

**Comment by parmentf** [comment]
Not the same as #369 but near.

**Comment by touv** [comment]
see v8
