### ISSUE TITLE
Resource: don't display empty values

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#397]
![image](https://user-images.githubusercontent.com/595509/27905364-fafb90ac-623f-11e7-959e-0c4f621b3ae6.png)

In the resource page, when a field has no value, don't display the field (in the example, `Nom Editeur - forme abrégée`): that line is useless.

**Comment by touv** [comment]
it's fixed here, isn't it ? https://github.com/Inist-CNRS/lodex/pull/387/commits/f1d4e7711e3a7991a376388254de660f5635d75e

**Comment by parmentf** [comment]
Yes it is. Since v7.16.1.
