### ISSUE TITLE
improve ISTEX format

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#401]
like this
![image](https://user-images.githubusercontent.com/15609/28061837-3568fc58-662c-11e7-9a6a-72490b6a20ff.png)

https://www.gliffy.com/go/publish/12122418

**Comment by touv** [comment]
and configure how many item to display (5, 10, 15, ...)

**Comment by touv** [comment]
and add a searchbox

**Comment by parmentf** [comment]
Where should the configuration of how many items to display in the `istex` format?
Only in backoffice, or in frontoffice, for any user?

**Comment by parmentf** [comment]
Less results is better when there is many queries.
See `lodex-langpub-*`: http://192.168.31.146:49266/uid:/http%3A%2F%2Flexvo.org%2Fid%2Fiso639-3%2Feng

**Comment by parmentf** [comment]
Searchbox is a filter on the results, that is to say, adding characters to the original query:

- original query: `language:eng AND publicationDate:[2001 TO 2100]`
- searchbox: `ab` ==> query = `language:eng AND publicationDate:[2001 TO 2100] AND ab`

**Comment by touv** [comment]
fix in v8
