### ISSUE TITLE
delete all mp-* collection after each update

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#404]
`/reduce` route create `mp_*` collection in mongoDB, but this collection is outdated after any field update. We need to drop it !

see
- https://github.com/Inist-CNRS/lodex/blob/master/src/api/controller/api/reduce.js#L48-L52

**Comment by parmentf** [comment]
Doc des reducers utilisés dans ezvis: http://ezvis.readthedocs.io/en/latest/Operators/ https://github.com/madec-project/ezvis/blob/master/doc/Operators.md

Les collections commençant par `mp_` sont des collections temporaires (jusqu'à la prochaine mise à jour).

À mon avis, c'est ailleurs dans le code qu'il faut supprimer ces collections, au moment où on met à jour les données (une fois que le jeu est publié).

Les reducers (comme `min`, `max`, `count`, `distinct`, ...) ne sont pas encore utilisés dans LODEX.
On trouve les identifiants des champs dans l'onglet ontologie (`Identifiant`).
Exemple: 
https://enrichmenttool-list-1.data.istex.fr/api/reduce/distinct/?field=EGLP 

qui renvoie:

```json
{
 "data": [
 {
  "_id": "alignement par traitements automatiques de masse",
  "value": 2
 },
 {
  "_id": "Catégorisation par apprentissage automatique",
  "value": 1
 },
 {
  "_id": "Indexation",
  "value": 1
 },
 {
  "_id": "Reconnaissance d'entités nommées",
  "value": 1
 },
 {
  "_id": "Science-Metrix : Catégorisation/appariement",
  "value": 1
 },
 {
  "_id": "Scopus : Catégorisation/appariement",
  "value": 1
 },
 {
  "_id": "Structuration des références bibliographiques",
  "value": 1
 },
 {
  "_id": "WoS : Catégorisation/appariement",
  "value": 1
 }
],
"total": 8
}
```

Après avoir lancé cette requête, dans mongo:

```mongo
> use enrichmenttool-list-1
switched to db enrichmenttool-list-1
> show collections
dataset
field
mp_03525930d3bca00aabe105bc4a6ee54ac9ceb560b98cf69b688d7e8d3b8144b3
mp_2b796bf4ee87bed5aab85cdd7128e004689dfd4ed23f68b42705db66fcaab162
mp_58ba50584219d60f6b2a6f2253f12b940d3c6415c585abc1d565481dbf3200de
publishedCharacteristic
publishedDataset
system.indexes
uriDataset
> db.mp_03525930d3bca00aabe105bc4a6ee54ac9ceb560b98cf69b688d7e8d3b8144b3.find()
{ "_id" : "Catégorisation par apprentissage automatique", "value" : 1 }
{ "_id" : "Indexation", "value" : 1 }
{ "_id" : "Reconnaissance d'entités nommées", "value" : 1 }
{ "_id" : "Science-Metrix : Catégorisation/appariement", "value" : 1 }
{ "_id" : "Scopus : Catégorisation/appariement", "value" : 1 }
{ "_id" : "Structuration des références bibliographiques", "value" : 1 }
{ "_id" : "WoS : Catégorisation/appariement", "value" : 1 }
{ "_id" : "alignement par traitements automatiques de masse", "value" : 2 }
```

**Comment by parmentf** [comment]
Useful: Robomongo (to navigate through data).

**Comment by touv** [comment]
useless see https://github.com/Inist-CNRS/lodex/pull/451
