### ISSUE TITLE
fold field at display

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#405]
In some cases, we have too much information to display, if we can fold a field, perhaps we can have a better display
![image](https://user-images.githubusercontent.com/15609/28117098-540d5fba-670c-11e7-94d8-c918050d4cba.png)

![image](https://user-images.githubusercontent.com/15609/28117104-5ff2a2f4-670c-11e7-95b7-197068c93409.png)

**Comment by parmentf** [comment]
Fold all fields with a level > 1
