### ISSUE TITLE
link to this dataset is not canonical url

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#407]
![image](https://user-images.githubusercontent.com/15609/28119290-95db61fa-6714-11e7-885b-f110ea3fa16d.png)

we should display "https://wos-category.data.istex.fr"  and use it in all social links

**Comment by parmentf** [comment]
See https://github.com/Inist-CNRS/lodex/blob/ff8cc3066df5b15e34a10ee9a7774fd4b6f91f38/src/app/js/public/Share.js

**Comment by touv** [comment]
<a href="https://trello.com/c/RxHNZvjl/175-proposer-une-url-canonique-dans-la-modal-dexport">Proposer une url canonique dans la modal d&#39;export</a>
