### ISSUE TITLE
Embedded view no longer works

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#408]
"Unexpected token % in JSON at position 0" 

https://loaded-corpus.data.istex.fr/api/widget?type=widget&fields=%255B%2522uri%2522%252C%2522FOmf%2522%252C%2522WHZy%2522%255D

**Comment by parmentf** [comment]
![image](https://user-images.githubusercontent.com/595509/28673110-f8ca9032-72e1-11e7-84e1-987a92872f0f.png)

**Comment by QuanticPotatoes** [comment]
Log from loaded-corpus : 
```
  SyntaxError: Unexpected token % in JSON at position 0
      at JSON.parse (<anonymous>)
      at Object.renderWidget (/app/src/api/controller/api/widget.js:16:60)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```
Impossible to reproduce the bug in the local's instance...
