### ISSUE TITLE
Upload image as field content

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#410]
Actually, we can display image from URL, but not all image have url. So we want to copy/paste an image to the file content to display it

**Comment by parmentf** [comment]
Store the file in the database.

**Comment by touv** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) As Julia, I want to copy/paste image directly in the value of a field](https://trello.com/c/m0re6ObQ/48-2-as-julia-i-want-to-copy-paste-image-directly-in-the-value-of-a-field)
