### ISSUE TITLE
no scheme in properties crash NQuads export

### ISSUE THREAD

**Issue by QuanticPotatoes** [Inist-CNRS/lodex#421]
In "film" use case. Some properties are in a composeOf and haven't scheme. 
![image](https://user-images.githubusercontent.com/7420853/29169152-d28327b2-7dd2-11e7-8ab5-48068b696e98.png)
Result, this lack crash the export.
Two solutions:
- Put a default scheme on unscheme properties
- Ignore unscheme properties

**Comment by parmentf** [comment]
I would say: ignore unschemed properties (that should already be the case).

**Comment by QuanticPotatoes** [comment]
Okay, it's fixed
