### ISSUE TITLE
Label of a field using format "URL externe" (link) does not take args into account

### ISSUE THREAD

**Issue by collignon88** [Inist-CNRS/lodex#445]
format URL externe doesn't display the right label : 
https://github.com/Inist-CNRS/lodex/blob/master/src/app/js/formats/link/Component.js

![image](https://user-images.githubusercontent.com/29753435/31078729-80dc5a48-a783-11e7-8204-874d79d41f41.png)

The field content is displayed instead of the field label.

![image](https://user-images.githubusercontent.com/29753435/31078800-c3996d08-a783-11e7-8882-92899a1e41bf.png)

**Comment by yannguillemin** [comment]
Sorry @collignon88 , but I have to close this issue because too old. Hoping that this was resolved at the time.
