### ISSUE TITLE
Sort by drag and drop does not work for collection fields added after publication

### ISSUE THREAD

**Issue by collignon88** [Inist-CNRS/lodex#446]
![image](https://user-images.githubusercontent.com/29753435/31081752-240f36fa-a78d-11e7-8a59-e6a774398882.png)

When a field which cover is `collection` is added after unpublishing dataset, its position in the Ontology view is last. (ex: classification MESH)

That would not be annoying if we could move it up to the previous fields covering `collection`,  but that it not possible: surrounded by `dataset`-covered fields, this one cannot move.

**Comment by touv** [comment]
fix in v8
