### ISSUE TITLE
Model broken at export when there are new fields

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#454]
1. add new dataset field
2. export model on the onlogy tab
3. reload model in new lodex
4. Admin dashboard crashed

In the json model file, new fields havent got transformers keys.

**Comment by touv** [comment]
![image](https://user-images.githubusercontent.com/15609/31827528-4ad3fddc-b5b8-11e7-97d5-6ad7078b90d6.png)

**Comment by yannguillemin** [comment]
Sorry @touv, but I have to close this issue because too old (comme convenu). Hoping that this was resolved at the time.
