### ISSUE TITLE
add an anchor for each field

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#457]
like github...

![image](https://user-images.githubusercontent.com/15609/31770798-c5e63aa6-b4d9-11e7-8341-0bdc155bd261.png)

**Comment by parmentf** [comment]
See #461

**Comment by touv** [comment]
ou aurait ainsi :

http://uri/1#2D34

et 

http://uri/1#compose/2D34D

**Comment by touv** [comment]
<blockquote class="trello-card"><a href="https://trello.com/c/Fd5wWe3i/115-rendre-accessible-cette-url-https-dataistexfr-af0d">rendre accessible cette url https://data.istex.fr/#af0d</a></blockquote>
