### ISSUE TITLE
Write documentation for new formats

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#469]
New formats have been introduced, we should document them in [lodex-users-doc](https://github.com/Inist-CNRS/lodex-users-doc/blob/master/docs/formats.md):
- emphased-number c04bde6dc8eb57e407d7adc41b2fc85ee49eaef5
- identifier-badge a6e2b9bab0c47e93b4530a8d132ae00a7f140779
- sentence b8b8fc2a5423debf7cae2058ffc47b7bbcec8bef

**Comment by touv** [comment]
see https://lodex.gitbooks.io/lodex-user-documentation/Administration/Mod%C3%A8le/Format/
