### ISSUE TITLE
v8.16.0: /Iogin is broken

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#619]
After having launched lodex, pointing the browser (Google Chrome 63) to the URL gives a useless /login page, where the button is not active.

![image](https://user-images.githubusercontent.com/595509/35728247-4931d4ea-080b-11e8-9c48-ef45432bea29.png)

I think it's due to the `Uncaught SyntaxError: Unexpected token <` at first line of the /login page (`<!DOCTYPE html>`), but I don't understand why this is taken as an error.

**Comment by parmentf** [comment]
Maybe it's important: in lodex log, after accessing the home page, I get that warning:

```
api_1       | Warning: Unknown prop `onTouchTap` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
api_1       |     in button (created by EnhancedButton)
api_1       |     in EnhancedButton (created by FlatButton)
api_1       |     in FlatButton (created by ButtonWithStatus)
api_1       |     in ButtonWithStatus (created by Unknown)
api_1       |     in div (created by CardActions)
api_1       |     in CardActions (created by Unknown)
api_1       |     in div (created by Card)
api_1       |     in div (created by Paper)
api_1       |     in Paper (created by Card)
api_1       |     in Card (created by Unknown)
api_1       |     in Unknown (created by Translated(Component))
api_1       |     in Translated(Component) (created by Connect(Translated(Component)))
api_1       |     in Connect(Translated(Component)) (created by RouterContext)
api_1       |     in div (created by Unknown)
api_1       |     in Unknown (created by RouterContext)
api_1       |     in RouterContext
api_1       |     in MuiThemeProvider
api_1       |     in Provider
```

**Comment by parmentf** [comment]
En supprimant la ligne avec l'attribut onTouchTap dans Login.js, ça ne change rien, l'erreur de syntaxe est toujours là (logique, ça n'a rien à voir, mais ça valait le coup de vérifier si ce n'était pas un effet de bord).

**Comment by parmentf** [comment]
Quand on supprimer le `userAuth` dans la config, tout se passe bien.
Pour se connecter à l'admin on passe par /admin#/login (qui marche), alors que pour la /home, c'est /login (qui ne marche pas).

**Comment by touv** [comment]
La page /login cherche à charger le fichier /index.js qui renvoie vers la page /login 
![image](https://user-images.githubusercontent.com/15609/35780789-2601f4be-09e1-11e8-9eb8-86ea13abc6a8.png)

**Comment by parmentf** [comment]
This is solved. A long time ago. Maybe 8.16.1 ?
