### ISSUE TITLE
Component update called multiples times after admin params update

### ISSUE THREAD

**Issue by youlot** [Inist-CNRS/lodex#916]
When updating component admin settings the component update multiples times. 
Use case : 
- set a log in the `componentDidUpdate` method of NetworkView (NetworkView.js).
- in a test instance save the new admin parameters and observe the logs : 

![update_component](https://user-images.githubusercontent.com/43371688/55226308-f5501300-5214-11e9-965a-1f374d9639ab.png)

As we can see on this screenshot the update is called multiple times.

**Comment by yannguillemin** [comment]
Sorry @youlot , but I have to close this issue because too old. Hoping that this was resolved at the time.
